// Package derived is the one catalog of generated outputs: which files a generator writes, with which marker or region, from which inputs.
// See docs/architecture/packages/internal-derived.md.
package derived

import (
	"path"
	"strings"
)

type GoInputSet string

const (
	CodeRegistrars    GoInputSet = "code-registrars"
	SkillcheckClosure GoInputSet = "closure:go/internal/skillcheck"
)

type GoInputDirs map[GoInputSet][]string

type Output struct {
	Pattern string
	Region  string
	Marker  string
}

type Entry struct {
	Name     string
	Outputs  []Output
	Inputs   []string
	GoInputs GoInputSet
	Generate []string
	Check    []string
}

const commandStubMarker = "<!-- GENERATED by `evolve skills generate` from skills/"

func Catalog() []Entry {
	return []Entry{
		{
			Name:     "flag-index",
			Outputs:  []Output{{Pattern: "docs/architecture/control-flags.md", Region: "GENERATED:flag-index"}},
			Inputs:   []string{"go/internal/flagregistry/"},
			Generate: []string{"flags", "generate"},
			Check:    []string{"flags", "check"},
		},
		{
			Name:     "signal-codes",
			Outputs:  []Output{{Pattern: "docs/architecture/signal-codes.md", Region: "GENERATED:signal-codes"}},
			GoInputs: CodeRegistrars,
			Generate: []string{"signals", "codes", "generate"},
			Check:    []string{"signals", "codes", "check"},
		},
		{
			Name: "skill-projections",
			Outputs: []Output{
				{Pattern: "commands/*.md", Marker: commandStubMarker},
				{Pattern: ".codex-plugin/plugin.json"},
				{Pattern: ".agents/plugins/marketplace.json"},
				{Pattern: "skills/*/SKILL.md", Region: "GENERATED:phase-facts"},
			},
			Inputs: []string{
				"skills/", "agents/", ".claude-plugin/plugin.json", "docs/architecture/phase-registry.json",
				".evolve/phases/", ".evolve/profiles/",
			},
			GoInputs: SkillcheckClosure,
			Generate: []string{"skills", "generate"},
			Check:    []string{"skills", "check"},
		},
	}
}

func Lookup(name string) (Entry, bool) {
	for _, e := range Catalog() {
		if e.Name == name {
			return e, true
		}
	}
	return Entry{}, false
}

func OutputOf(relPath string) (Entry, Output, bool) {
	for _, e := range Catalog() {
		if o, ok := e.outputOf(relPath); ok {
			return e, o, true
		}
	}
	return Entry{}, Output{}, false
}

func (e Entry) outputOf(relPath string) (Output, bool) {
	for _, o := range e.Outputs {
		if matched, _ := path.Match(o.Pattern, relPath); matched {
			return o, true
		}
	}
	return Output{}, false
}

func (o Output) begin() string { return "<!-- " + o.Region + " BEGIN" }

func (o Output) end() string { return "<!-- " + o.Region + " END" }

func (e Entry) Pathspecs() []string {
	specs := make([]string, 0, len(e.Outputs))
	for _, o := range e.Outputs {
		specs = append(specs, o.Pattern)
	}
	return specs
}

func (e Entry) touchesInput(paths []string, dirs GoInputDirs) bool {
	for _, p := range paths {
		if e.isInput(p, dirs[e.GoInputs]) {
			return true
		}
	}
	return false
}

func (e Entry) isInput(p string, goDirs []string) bool {
	for _, in := range e.Inputs {
		if p == in || (strings.HasSuffix(in, "/") && strings.HasPrefix(p, in)) {
			return true
		}
	}
	dir := path.Dir(p)
	for _, d := range goDirs {
		if dir == d {
			return true
		}
	}
	return false
}

func (e Entry) touchesOutput(paths []string) bool {
	for _, p := range paths {
		if _, ok := e.outputOf(p); ok {
			return true
		}
	}
	return false
}

func Stale(changed []string, dirs GoInputDirs) []Entry {
	var stale []Entry
	for _, e := range Catalog() {
		if e.touchesInput(changed, dirs) {
			stale = append(stale, e)
		}
	}
	return stale
}

func Fires(lane, peer, conflicted []string, dirs GoInputDirs) []Entry {
	var fired []Entry
	for _, e := range Catalog() {
		if e.touchesOutput(conflicted) || e.crossStale(lane, peer, dirs) || e.crossStale(peer, lane, dirs) {
			fired = append(fired, e)
		}
	}
	return fired
}

func (e Entry) crossStale(one, other []string, dirs GoInputDirs) bool {
	return e.touchesInput(one, dirs) && (e.touchesInput(other, dirs) || e.touchesOutput(other))
}
