package inboxmover

// lifecycle_golden_test.go — ADR-0103 unit 06 step 0: characterization goldens
// captured on the pre-extraction code (8e8f080f) and replayed byte-for-byte
// through the lifecycle leaf's facades. Roots and the pid are templated
// ({{ROOT}}, {{PID}}); the chained ledger's prev_hash (which covers absolute
// paths) is templated to {{HASH}}. No golden is regenerated by a flag: a drift
// is a declared deviation with its own commit, never a silent re-capture.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"
)

var fixedLifecycleClock = time.Date(2026, 5, 24, 12, 0, 0, 0, time.UTC)

// goldenTemplate maps the environment-specific bytes of got onto the golden's
// placeholders so one file serves every machine.
func goldenTemplate(got, root string) string {
	got = strings.ReplaceAll(got, root, "{{ROOT}}")
	got = strings.ReplaceAll(got, ".tmp."+strconv.Itoa(os.Getpid()), ".tmp.{{PID}}")
	return regexp.MustCompile(`"prev_hash":"[0-9a-f]{64}"`).ReplaceAllString(got, `"prev_hash":"{{HASH}}"`)
}

func readGolden(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("golden %s: %v", name, err)
	}
	return string(b)
}

func assertGolden(t *testing.T, name, got, root string) {
	t.Helper()
	if templated, want := goldenTemplate(got, root), readGolden(t, name); templated != want {
		t.Errorf("%s drifted from the golden captured on 8e8f080f:\n--- got ---\n%s\n--- want ---\n%s", name, templated, want)
	}
}

// treeOf lists every path under dir (files and directories, sorted, relative,
// directories marked with a trailing slash).
func treeOf(t *testing.T, dir string) string {
	t.Helper()
	var lines []string
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(dir, path)
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			rel += "/"
		}
		lines = append(lines, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n") + "\n"
}

func writeItemAt(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func mustMkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatal(err)
	}
}

func mustRemove(t *testing.T, path string) {
	t.Helper()
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
}

// goldenOptions is the Center-less Options every golden runs through: a fixed
// clock, a captured stderr, an injected landing probe (git-less) and an
// injected active-cycle reader.
func goldenOptions(repo string, stderr *strings.Builder) Options {
	return Options{
		ProjectRoot:   repo,
		Stderr:        stderr,
		Now:           func() time.Time { return fixedLifecycleClock },
		IsLandedFn:    func(sha string) (bool, error) { return sha != "unlanded00", nil },
		ActiveCycleFn: func() (string, error) { return "13", nil },
	}
}

// Test 1 — claim → promote processed with a sha → the residual drain: the
// ledger, the stderr and the final tree.
func TestGolden_ClaimPromoteRelease(t *testing.T) {
	repo := makeRepo(t)
	var stderr strings.Builder
	opts := goldenOptions(repo, &stderr)
	dropInboxFile(t, repo, "task-1.json", "task-1")
	dropInboxFile(t, repo, "task-2.json", "task-2")
	if _, err := Claim(opts, "task-1", "7"); err != nil {
		t.Fatal(err)
	}
	if _, err := Claim(opts, "task-2", "7"); err != nil {
		t.Fatal(err)
	}
	if _, err := Promote(opts, "task-1", "processed", PromoteOpts{Cycle: "7", CommitSHA: "abcdef1234567890"}); err != nil {
		t.Fatal(err)
	}
	if _, err := ReleaseCycleProcessing(opts, 7); err != nil {
		t.Fatal(err)
	}
	assertGolden(t, "g1.ledger.golden", readLedger(t, repo), repo)
	assertGolden(t, "g1.stderr.golden", stderr.String(), repo)
	assertGolden(t, "g1.tree.golden", treeOf(t, filepath.Join(repo, ".evolve", "inbox")), repo)
}

// Test 2 — the FAIL drain at the ceiling: the quarantined item's bytes (count
// 2, the reason, no continuation), the stderr order and the ledger.
func TestGolden_FailDrain_QuarantineAtCeiling(t *testing.T) {
	repo := makeRepo(t)
	var stderr strings.Builder
	opts := goldenOptions(repo, &stderr)
	inbox := filepath.Join(repo, ".evolve", "inbox")
	writeItemAt(t, filepath.Join(inbox, "processing", "cycle-5", "task-a.json"),
		`{"id":"task-a","title":"A","failure_count":1,"continuation":{"snapshot_sha":"abc123","cycle":4},"zeta":true}`)
	writeItemAt(t, filepath.Join(inbox, "processing", "cycle-5", "task-b.json"), `{"id":"task-b","title":"B"}`)
	writeItemAt(t, filepath.Join(repo, ".evolve", "runs", "cycle-5", "continuation-manifest.json"), `{"snapshot_sha":"abc123","cycle":5}`)
	res, err := ApplyCycleOutcome(opts, CycleOutcome{Cycle: 5, CommittedIDs: []string{"task-a"}, Ceiling: 2})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Quarantined) != 1 || len(res.Released) != 1 {
		t.Fatalf("res = %+v", res)
	}
	item, err := os.ReadFile(filepath.Join(inbox, "quarantine", "task-a.json"))
	if err != nil {
		t.Fatal(err)
	}
	assertGolden(t, "g2.item.golden", string(item), repo)
	assertGolden(t, "g2.stderr.golden", stderr.String(), repo)
	assertGolden(t, "g2.ledger.golden", readLedger(t, repo), repo)
}

// Test 3 — RecoverOrphans skips the active cycle and recovers the dead one.
func TestGolden_RecoverOrphans_ActiveSkipped(t *testing.T) {
	repo := makeRepo(t)
	var stderr strings.Builder
	opts := goldenOptions(repo, &stderr)
	opts.ActiveCycleFn = nil // the default reader over cycle-state.json
	setCycleState(t, repo, "2")
	dropProcessingFile(t, repo, "1", "task-a.json", "task-a")
	dropProcessingFile(t, repo, "2", "task-b.json", "task-b")
	res, err := RecoverOrphans(opts)
	if err != nil || res.Recovered != 1 {
		t.Fatalf("res = %+v, err = %v", res, err)
	}
	assertGolden(t, "g3.stderr.golden", stderr.String(), repo)
	assertGolden(t, "g3.ledger.golden", readLedger(t, repo), repo)
}

// Test 4 — ReleaseFromQuarantine rewrites the item (sorted keys, count 0, the
// reason deleted) and records the release.
func TestGolden_ReleaseFromQuarantine_ItemBytes(t *testing.T) {
	repo := makeRepo(t)
	var stderr strings.Builder
	opts := goldenOptions(repo, &stderr)
	inbox := filepath.Join(repo, ".evolve", "inbox")
	writeItemAt(t, filepath.Join(inbox, "quarantine", "task-q.json"),
		`{"zeta": 1, "id": "task-q", "failure_count": 3, "last_failure_reason": "boom", "alpha": {"b": 2, "a": [1, 2]}}`)
	if _, err := ReleaseFromQuarantine(opts, "task-q"); err != nil {
		t.Fatal(err)
	}
	item, err := os.ReadFile(filepath.Join(inbox, "task-q.json"))
	if err != nil {
		t.Fatal(err)
	}
	assertGolden(t, "g4.item.golden", string(item), repo)
	assertGolden(t, "g4.stderr.golden", stderr.String(), repo)
	assertGolden(t, "g4.ledger.golden", readLedger(t, repo), repo)
}

// lifecycleSequence is the §6 test-5 script: one provoked fault per replaced
// stderr line class (the fifteen sites), plus the kept INFO and usage lines,
// over ONE repo. mk builds the Options for every call so the Center-less golden
// (test 5) and the wired-root golden (test 51) run the identical script.
func lifecycleSequence(t *testing.T, repo string, mk func() Options) {
	t.Helper()
	inbox := filepath.Join(repo, ".evolve", "inbox")
	proc := func(cycle int, name string) string {
		return filepath.Join(inbox, "processing", fmt.Sprintf("cycle-%d", cycle), name)
	}
	// :201 — a claim of an id the root does not hold.
	_, _ = Claim(mk(), "t1", "7")
	// :205 — a console-routed item.
	writeItemAt(t, filepath.Join(inbox, "c1.json"), `{"id":"c1","route":"console-manual"}`)
	_, _ = Claim(mk(), "c1", "7")
	// :217 — a FILE at processing/ makes the cycle dir's mkdir fail.
	writeItemAt(t, filepath.Join(inbox, "t1.json"), `{"id":"t1","payload":"x"}`)
	writeItemAt(t, filepath.Join(inbox, "processing"), "x")
	_, _ = Claim(mk(), "t1", "7")
	mustRemove(t, filepath.Join(inbox, "processing"))
	// :221 — a directory at the destination file path makes the rename fail.
	mustMkdirAll(t, proc(7, "t1.json"))
	_, _ = Claim(mk(), "t1", "7")
	mustRemove(t, proc(7, "t1.json"))
	_, _ = Claim(mk(), "t1", "7") // :226 + the claim ledger line
	_, _ = Claim(mk(), "", "7")   // :196 usage (kept verbatim)
	_, _ = Claim(mk(), "t1", "x") // :201 again (t1 is claimed) — route precedes the cycle check
	// :298 — a promote of an id nobody holds.
	_, _ = Promote(mk(), "ghost", "processed", PromoteOpts{Cycle: "7"})
	_, _ = Promote(mk(), "t1", "bogus", PromoteOpts{}) // :285 (kept verbatim)
	// :320 — an unlanded sha reroutes to retry/.
	_, _ = Promote(mk(), "t1", "processed", PromoteOpts{Cycle: "7", CommitSHA: "unlanded00"})
	// :336 — a FILE at processed/ makes the destination mkdir fail.
	writeItemAt(t, proc(7, "t2.json"), `{"id":"t2"}`)
	writeItemAt(t, filepath.Join(inbox, "processed"), "x")
	_, _ = Promote(mk(), "t2", "processed", PromoteOpts{Cycle: "7"})
	mustRemove(t, filepath.Join(inbox, "processed"))
	// :349 — a directory at the destination basename makes the rename fail.
	mustMkdirAll(t, filepath.Join(inbox, "processed", "cycle-7", "t2.json"))
	_, _ = Promote(mk(), "t2", "processed", PromoteOpts{Cycle: "7"})
	mustRemove(t, filepath.Join(inbox, "processed", "cycle-7", "t2.json"))
	_, _ = Promote(mk(), "t2", "processed", PromoteOpts{Cycle: "7", CommitSHA: "abcdef1234567890"}) // :365
	// :699 + :755 — a DIRECTORY at the manifest path; a root twin of t3.
	mustMkdirAll(t, filepath.Join(repo, ".evolve", "runs", "cycle-8", "continuation-manifest.json"))
	writeItemAt(t, filepath.Join(inbox, "t3.json"), `{"id":"t3-root"}`)
	writeItemAt(t, proc(8, "t3.json"), `{"id":"t3"}`)
	writeItemAt(t, proc(8, "t4.json"), `{"id":"t4"}`)
	_, _ = ReleaseCycleProcessing(mk(), 8)
	// :764 — a directory at <path>.tmp.<pid> makes the continuation stamp fail.
	writeItemAt(t, filepath.Join(repo, ".evolve", "runs", "cycle-9", "continuation-manifest.json"), `{"snapshot_sha":"abc123","cycle":9}`)
	writeItemAt(t, proc(9, "t5.json"), `{"id":"t5"}`)
	mustMkdirAll(t, proc(9, "t5.json.tmp."+strconv.Itoa(os.Getpid())))
	_, _ = ReleaseCycleProcessing(mk(), 9)
	// :768 — the cycle dir made non-writable makes the release rename fail.
	writeItemAt(t, proc(10, "t6.json"), `{"id":"t6"}`)
	lockDir(t, proc(10, ""))
	_, _ = ReleaseCycleProcessing(mk(), 10)
	unlockDir(t, proc(10, ""))
	if _, err := os.Stat(proc(10, "t6.json")); err != nil {
		t.Fatalf("the read-only cycle dir must have kept t6 (the fault did not happen): %v", err)
	}
	// :739 — a FILE at quarantine/: the park's mkdir fails, the item releases.
	writeItemAt(t, proc(11, "t7.json"), `{"id":"t7"}`)
	writeItemAt(t, filepath.Join(inbox, "quarantine"), "x")
	_, _ = ApplyCycleOutcome(mk(), CycleOutcome{Cycle: 11, CommittedIDs: []string{"t7"}, Ceiling: 1})
	mustRemove(t, filepath.Join(inbox, "quarantine"))
	// :742 — a DIRECTORY at quarantine/<base>: the park's rename fails (NoOp).
	writeItemAt(t, proc(12, "t8.json"), `{"id":"t8"}`)
	mustMkdirAll(t, filepath.Join(inbox, "quarantine", "t8.json"))
	_, _ = ApplyCycleOutcome(mk(), CycleOutcome{Cycle: 12, CommittedIDs: []string{"t8"}, Ceiling: 1})
	// :478 — an operator release out of quarantine.
	writeItemAt(t, filepath.Join(inbox, "quarantine", "q1.json"), `{"id":"q1","failure_count":3,"last_failure_reason":"x"}`)
	_, _ = ReleaseFromQuarantine(mk(), "q1")
	// :582 / :595 / :598 / :611 — the active cycle skipped, a root directory
	// twin fails the move, a clean orphan recovers (and cycle-8's t3 clobbers
	// its root twin — the preserved quirk).
	writeItemAt(t, proc(13, "t9.json"), `{"id":"t9"}`)
	writeItemAt(t, proc(14, "t10.json"), `{"id":"t10"}`)
	mustMkdirAll(t, filepath.Join(inbox, "t10.json"))
	writeItemAt(t, proc(14, "t11.json"), `{"id":"t11"}`)
	_, _ = RecoverOrphans(mk())
}

// lockDir removes write permission from dir (restored by unlockDir and on
// cleanup); the caller asserts the fault it wanted actually happened, so a
// root run fails loudly instead of skipping.
func lockDir(t *testing.T, dir string) {
	t.Helper()
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })
}

func unlockDir(t *testing.T, dir string) {
	t.Helper()
	if err := os.Chmod(dir, 0o755); err != nil {
		t.Fatal(err)
	}
}

// Test 5 — the Center-less byte-identity proof: the scripted sequence's stderr
// and ledger equal the goldens captured before the move.
func TestGolden_LifecycleSequence_StderrAndLedger(t *testing.T) {
	repo := makeRepo(t)
	var stderr strings.Builder
	lifecycleSequence(t, repo, func() Options { return goldenOptions(repo, &stderr) })
	assertGolden(t, "sequence.stderr.golden", stderr.String(), repo)
	assertGolden(t, "sequence.ledger.golden", readLedger(t, repo), repo)
}
