package router_test

// Pure-kernel scenario catalog for the dynamic phase-routing decision. Built
// entirely from the configurable routingtest framework: each test is a data
// spec; combinations are generated by Matrix. See internal/routingtest.

import (
	"testing"

	"github.com/mickeyyaya/evolve-loop/go/internal/config"
	. "github.com/mickeyyaya/evolve-loop/go/internal/routingtest"
)

// TestKernelScenarios runs the explicit single-decision catalog.
func TestKernelScenarios(t *testing.T) {
	RunAll(t, kernelCatalog())
}

func kernelCatalog() []ScenarioSpec {
	return []ScenarioSpec{
		Scenario("start->scout default",
			Pure(), At("start"), ExpectNext("scout"), ExpectReason("spine:scout")),
		Scenario("start->intent when forced",
			Pure(), At("start"), PhaseEnabled("intent", config.EnableOn),
			ExpectNext("intent"), ExpectInserts("intent"), ExpectReason("forced-on:intent")),

		Scenario("scout->tdd small",
			Pure(), At("scout"), Done("scout"), SmallCycle(),
			ExpectNext("tdd"), ExpectReason("conditional-pin:tdd")),
		Scenario("scout->tdd medium skips triage",
			Pure(), At("scout"), Done("scout"), MediumCycle(),
			ExpectNext("tdd"), ExpectSkips("triage"), ExpectReason("conditional-pin:tdd")),
		Scenario("scout->tdd large",
			Pure(), At("scout"), Done("scout"), LargeCycle(),
			ExpectNext("tdd"), ExpectReason("conditional-pin:tdd")),
		Scenario("scout->build trivial skips tdd",
			Pure(), At("scout"), Done("scout"), TrivialCycle(),
			ExpectNext("build"), ExpectSkips("tdd"), ExpectReason("spine:build")),

		Scenario("triage refines scout to tdd",
			Pure(), At("triage"), Done("scout", "triage"), TrivialCycle(), TriageSize("medium"),
			ExpectNext("tdd"), ExpectReason("conditional-pin:tdd")),

		Scenario("build->tester on acs_red",
			Pure(), At("build"), Done("scout", "tdd", "build"), RedBuild(2),
			ExpectNext("tester"), ExpectInserts("tester"), ExpectReason("content-insert:tester")),
		Scenario("build->audit on green skips tester",
			Pure(), At("build"), Done("scout", "tdd", "build"), GreenBuild(),
			ExpectNext("audit"), ExpectSkips("tester"), ExpectReason("spine:audit")),
		Scenario("build->tester on severity HIGH",
			Pure(), At("build"), Done("scout", "tdd", "build"), Severity("HIGH"), SeverityTrigger(),
			ExpectNext("tester"), ExpectInserts("tester")),
		Scenario("build severity MEDIUM below HIGH threshold",
			Pure(), At("build"), Done("scout", "tdd", "build"), Severity("MEDIUM"), SeverityTrigger(),
			ExpectNext("audit"), ExpectSkips("tester")),

		Scenario("audit PASS->ship",
			Pure(), At("audit"), Done("scout", "build", "audit"), CompletedVerdict("PASS"),
			ExpectNext("ship"), ExpectReason("spine:ship")),
		Scenario("audit WARN->ship",
			Pure(), At("audit"), Done("scout", "build", "audit"), CompletedVerdict("WARN"),
			ExpectNext("ship")),
		Scenario("audit FAIL->retrospective",
			Pure(), At("audit"), Done("scout", "build", "audit"), CompletedVerdict("FAIL"),
			ExpectNext("retrospective"), ExpectReason("audit-fail-to-retrospective")),
		Scenario("audit FAIL retro-off->end",
			Pure(), At("audit"), Done("scout", "build", "audit"), CompletedVerdict("FAIL"),
			PhaseEnabled("retrospective", config.EnableOff), ExpectNext("end")),

		Scenario("mandatory clamp ship=off forced on",
			Pure(), At("audit"), Done("scout", "build", "audit"), CompletedVerdict("PASS"),
			PhaseEnabled("ship", config.EnableOff),
			ExpectNext("ship"), ExpectClamp("mandatory-never-skipped")),
		Scenario("budget exhausted drops tester",
			Pure(), At("build"), Done("scout", "tdd", "build"), RedBuild(5), Budget(-1),
			ExpectNext("audit"), ExpectSkips("tester"), ExpectClamp("budget-exhausted")),
		Scenario("max-insertions cap drops tester",
			Pure(), At("build"), Done("scout", "tdd", "build", "plan-review"), RedBuild(5), MaxInserts(1),
			ExpectNext("audit"), ExpectSkips("tester"), ExpectClamp("max-insertions-cap")),

		// Simulated agent at the pure layer.
		Scenario("LLM agrees no clamp",
			Pure(), At("build"), Done("scout", "tdd", "build"), GreenBuild(), Agent("build", "audit"),
			ExpectNext("audit"), ExpectInvariants("proposal-never-weakens", "determinism")),
		Scenario("LLM legal-divergent insert adopted",
			Pure(), At("build"), Done("scout", "tdd", "build"), RedBuild(2), Agent("build", "tester"),
			ExpectNext("tester"), ExpectInserts("tester")),
		Scenario("LLM illegal ship-from-build clamped",
			Pure(), At("build"), Done("scout", "tdd", "build"), GreenBuild(), Agent("build", "ship"),
			ExpectNext("audit"), ExpectClamp("llm-proposal-clamped")),
	}
}

// TestKernelInvariants asserts the non-bypassable floor over an adversarial
// cross-product: for EVERY (phase × cycle-size × build × budget × agent move),
// the kernel disposes — no adversarial proposal weakens it.
func TestKernelInvariants(t *testing.T) {
	specs := Matrix(
		[]Brick{Pure(), ExpectInvariants(
			"proposal-never-weakens", "mandatory-never-skipped", "no-ship-before-audit",
			"tdd-pin-nontrivial", "insert-le-cap", "budget-zero-no-content-insert", "determinism",
		)},
		Dim("at",
			V("scout", At("scout"), Done("scout")),
			V("build", At("build"), Done("scout", "tdd", "build")),
			V("audit", At("audit"), Done("scout", "build", "audit"), CompletedVerdict("PASS")),
		),
		Dim("size", V("trivial", TrivialCycle()), V("medium", MediumCycle())),
		Dim("build", V("green", GreenBuild()), V("red", RedBuild(3))),
		Dim("budget", V("ok"), V("zero", Budget(-1))),
		Dim("agent",
			V("none"),
			V("ship", Agent("build", "ship")),
			V("end", Agent("scout", "end")),
			V("memo", Agent("build", "memo")),
		),
	)
	RunAll(t, specs)
}
