// Package routingtest is a configurable, composable ("Lego") test framework for
// the dynamic phase-routing kernel. A scenario is pure data (ScenarioSpec)
// assembled from Bricks (bricks.go) and/or generated by Matrix (matrix.go); the
// engine (engine.go) interprets each spec against a selectable Surface and
// self-validates the embedded expectations. Adding a test == adding a config;
// covering a new combination == composing existing bricks or adding a Matrix
// dimension.
//
// The package is intentionally a plain (non-_test) package so external test
// packages (router_test, core_test) can import it. It imports core + router +
// config; nothing imports it except *_test.go, so there is no production cycle.
package routingtest

import (
	"github.com/mickeyyaya/evolve-loop/go/internal/config"
	"github.com/mickeyyaya/evolve-loop/go/internal/core"
	"github.com/mickeyyaya/evolve-loop/go/internal/router"
)

// Surface selects how a ScenarioSpec is executed.
type Surface int

const (
	// PureKernel runs a single router.Route() decision (no I/O, fast).
	PureKernel Surface = iota
	// FullOrchestrator runs an end-to-end core.Orchestrator.RunCycle.
	FullOrchestrator
)

// nonExpiredRecordedAt is a far-future RecordedAt so a seeded failure stays
// inside its retention window regardless of wall-clock (mirrors the existing
// retro tests in orchestrator_test.go).
const nonExpiredRecordedAt = "2099-01-01T00:00:00Z"

// ScenarioSpec is the complete declarative description of one routing test —
// the single baseplate every Brick snaps onto. Zero values resolve to safe
// defaults in engine.go (Stage:Off, default spine, tester trigger acs_red>0).
type ScenarioSpec struct {
	Name    string
	Surface Surface

	// --- routing config knobs ---
	Stage         config.Stage
	Mode          config.Mode
	Mandatory     []string
	Conditional   map[string]config.CondRule
	Enable        map[string]config.Enable
	Triggers      map[string]config.RoutingBlock
	MaxInsertions int     // 0 → default 4
	BudgetUSD     float64 // 0 → default 100 (positive ⇒ content inserts not budget-clamped)

	// --- world fixtures ---
	Signals SignalSpec
	Env     map[string]string

	// --- PureKernel-only ---
	Current   string
	Verdict   string
	Completed []string

	// --- FullOrchestrator-only ---
	Verdicts  map[string]string // phase name → fakeRunner verdict
	FailedAt  []FailedRecordSpec
	LastCycle int

	// --- the simulated dynamic agent + expectations ---
	Agent  AgentSpec
	Expect ExpectSpec
}

// SignalSpec is ONE objective-signal fixture, rendered two ways: Signals() for
// the pure kernel and HandoffFiles() for the orchestrator's Digest. The
// consistency test (consistency_test.go) proves the two renderings agree.
type SignalSpec struct {
	CycleSize      string // scout cycle_size_estimate
	TriageSize     string // triage refinement (overrides scout per CycleSize())
	ACSRed         int
	ACSGreen       int
	ACSRegression  int
	FilesTouched   int
	SeverityMax    string // "LOW"|"MEDIUM"|"HIGH"|"CRITICAL"
	BuildVerdict   string
	AuditVerdict   string
	AuditConf      float64
	AuditRedCount  int
	ScoutItemCount int
	ScoutCarryover int
}

// AgentSpec is the simulated LLM router brain: a scripted proposal per
// just-completed phase, or a forced error (to exercise degrade-to-static).
type AgentSpec struct {
	Proposals map[string]*router.Proposal // RouteInput.Current → proposal
	ErrorsOn  map[string]bool             // RouteInput.Current → return error
}

// active reports whether a real agent is configured (⇒ LLMProposal strategy).
func (a AgentSpec) active() bool { return len(a.Proposals) > 0 || len(a.ErrorsOn) > 0 }

// FailedRecordSpec seeds one state.failedApproaches entry (the retro arc input).
// RecordedAt is set non-expired by the engine.
type FailedRecordSpec struct {
	Classification string
	Verdict        string
}

// ExpectSpec is the composable expectation set. Empty fields are not asserted.
type ExpectSpec struct {
	// PureKernel single-decision expectations.
	NextPhase string
	Inserts   []string
	Skips     []string
	Clamps    []string // clamp rule names that must be present
	Reason    string

	// FullOrchestrator expectations.
	PhaseSequence    []core.Phase // exact PhasesRun (when non-nil)
	PhasesAbsent     []core.Phase // these must NOT appear in PhasesRun
	DecisionInserts  []string     // some logged routing decision proposed these inserts
	DecisionClamps   []string     // some logged routing decision carries these clamps
	RoutingLedgerMin int          // ≥ this many routing_decision ledger entries
	RetroPrefix      string       // CycleResult.RetroDecision has this prefix

	// Both surfaces.
	Invariants []string // names resolved in invariants.go
}
