//go:build integration

package audit

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/mickeyyaya/evolve-loop/go/internal/core"
)

// writeGoPredFixture writes a minimal Go ACS predicate module under <root>/go so
// acssuite.Run's Go lane discovers one predicate for `cycle` (passing when pass)
// via real `go test -tags acs` execution.
func writeGoPredFixture(t *testing.T, root string, cycle int, pass bool) {
	t.Helper()
	pkg := "cycle" + strconv.Itoa(cycle)
	dir := filepath.Join(root, "go", "acs", pkg)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir preds: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "go", "go.mod"), []byte("module acsfixture\n\ngo 1.21\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	body := "//go:build acs\n\npackage " + pkg + "\n\nimport \"testing\"\n\nfunc TestC" + strconv.Itoa(cycle) + "_001_Fixture(t *testing.T) {\n"
	if !pass {
		body += "\tt.Fatal(\"fixture RED\")\n"
	}
	body += "}\n"
	if err := os.WriteFile(filepath.Join(dir, "predicates_test.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write predicate: %v", err)
	}
}

// TestNewDefault_WiresVerdictGenerator pins the cycle-147 fix: the audit phase
// constructed via NewDefault (the single seam now used by BOTH the registry
// init and the loop's runner map in cmd_cycle.go) must wire the REAL
// generateACSVerdict, so a missing acs-verdict.json is auto-generated host-side
// from the on-disk predicate suite — not force-FAILed. This exercises the real
// generateACSVerdict+acssuite path (unlike the fake-generator TestRun_Missing*
// tests) and would have failed against the pre-fix cmd_cycle.go wiring, which
// left GenerateVerdict nil.
func TestNewDefault_WiresVerdictGenerator(t *testing.T) {
	// Predicate root (the cycle worktree): one trivial passing Go predicate.
	root := t.TempDir()
	writeGoPredFixture(t, root, 7, true)

	// Workspace must be <evolveDir>/runs/cycle-7 so generateACSVerdict's
	// evolveDir = dirname(dirname(workspace)) lands the verdict exactly where
	// Classify reads it (<workspace>/acs-verdict.json).
	evolveDir := t.TempDir()
	ws := filepath.Join(evolveDir, "runs", "cycle-7")
	if err := os.MkdirAll(ws, 0o755); err != nil {
		t.Fatalf("mkdir ws: %v", err)
	}

	fb := &fakeBridge{writeArtifact: "# Audit Report\n\n## Verdict\n**PASS**\n"}
	phase := NewDefault(fb, fakePromptsFS("body"))

	resp, err := phase.Run(context.Background(), core.PhaseRequest{
		Cycle: 7, ProjectRoot: root, Worktree: root, Workspace: ws,
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}

	// The verdict file must now exist at the canonical path (it did NOT before
	// the wiring fix — that was the cycle-147 forced-FAIL).
	vb, readErr := os.ReadFile(filepath.Join(ws, "acs-verdict.json"))
	if readErr != nil {
		t.Fatalf("acs-verdict.json not generated by NewDefault: %v", readErr)
	}
	var v struct {
		RedCount       int `json:"red_count"`
		PredicateSuite struct {
			ThisCycleCount int `json:"this_cycle_count"`
		} `json:"predicate_suite"`
	}
	if err := json.Unmarshal(vb, &v); err != nil {
		t.Fatalf("verdict parse: %v", err)
	}
	if v.PredicateSuite.ThisCycleCount < 1 {
		t.Errorf("this_cycle_count=%d, want >=1 (the on-disk predicate must be discovered under Worktree)", v.PredicateSuite.ThisCycleCount)
	}
	if v.RedCount != 0 {
		t.Errorf("red_count=%d, want 0 (the only predicate exits 0)", v.RedCount)
	}
	if resp.Verdict != core.VerdictPASS {
		t.Errorf("Verdict=%q, want PASS", resp.Verdict)
	}
	if resp.NextPhase != "ship" {
		t.Errorf("NextPhase=%q, want ship", resp.NextPhase)
	}
}

// TestGenerateACSVerdict_EmptyWorktree_FallsBackToProjectRoot — Worktree==""
// must fall back to ProjectRoot as the predicate-discovery root. A passing
// predicate under ProjectRoot/acs/cycle-N is discovered and the verdict is
// written at <evolveDir>/runs/cycle-N/acs-verdict.json.
func TestGenerateACSVerdict_EmptyWorktree_FallsBackToProjectRoot(t *testing.T) {
	projectRoot := t.TempDir()
	writeGoPredFixture(t, projectRoot, 5, true)
	evolveDir := t.TempDir()
	ws := filepath.Join(evolveDir, "runs", "cycle-5")
	if err := os.MkdirAll(ws, 0o755); err != nil {
		t.Fatalf("mkdir ws: %v", err)
	}

	err := generateACSVerdict(core.PhaseRequest{
		Cycle: 5, ProjectRoot: projectRoot, Worktree: "", Workspace: ws,
	})
	if err != nil {
		t.Fatalf("generateACSVerdict: %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(ws, "acs-verdict.json")); statErr != nil {
		t.Errorf("verdict not written via ProjectRoot fallback: %v", statErr)
	}
}

// TestGenerateACSVerdict_WriteVerdictError_Propagates — when the suite is
// non-empty but WriteVerdict cannot create the cycle dir (here: the computed
// evolveDir is a regular FILE, so MkdirAll fails), generateACSVerdict must
// wrap and return the write error.
func TestGenerateACSVerdict_WriteVerdictError_Propagates(t *testing.T) {
	root := t.TempDir()
	writeGoPredFixture(t, root, 3, true)

	// evolveDir = dirname(dirname(workspace)). Make that path a regular file so
	// acssuite.WriteVerdict's MkdirAll(<evolveDir>/runs/cycle-3) fails.
	base := t.TempDir()
	blocker := filepath.Join(base, "blocker")
	if err := os.WriteFile(blocker, []byte("x"), 0o644); err != nil {
		t.Fatalf("write blocker file: %v", err)
	}
	// workspace such that dirname(dirname(ws)) == blocker (a file).
	ws := filepath.Join(blocker, "runs", "cycle-3")

	err := generateACSVerdict(core.PhaseRequest{
		Cycle: 3, ProjectRoot: root, Worktree: root, Workspace: ws,
	})
	if err == nil {
		t.Fatal("err=nil, want write-verdict error (evolveDir is a file)")
	}
	if !strings.Contains(err.Error(), "write verdict") {
		t.Errorf("err=%v, want wrapped 'write verdict'", err)
	}
}
