package flagregistry

// registry_table.go — the flag data. Seeded mechanically 2026-06-11 from the
// repo-wide inventory + control-flags.md tables; hand-maintained since.
// KEEP SORTED BY NAME (Lookup binary-searches; the test enforces order).

var All = []Flag{
	{Name: "EVOLVE_ACS_GO_TIMEOUT_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ACS_PREDICATE_TIMEOUT_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ADAPTERS_DIR_OVERRIDE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_AGY_REQUIRE_FULL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_ALLOW_DEEP_RESEARCH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ALLOW_DOC_DELETE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ALLOW_INTERACTIVE_FALLBACK", Status: StatusDead, Cluster: "Platform / CLI Hybrid", Doc: "Opt-in to interactive-mode fallback [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_ANCHOR_EXTRACT", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "v8.63.0 Campaign C (Tier 3 — anchored artifacts). When `1`, role-context-builder.sh extracts only named `<!-- ANCHOR:<name> -->` regions from prior phase artifacts instead of `cat`-ing whole files. Persona templates (scout/builder/auditor/retrospective) emit anchor markers around output sections. Backwards-compat: pre-v8.63 artifacts without anchors fall back to full-file emission once per file (no duplication regression). Auditor reads `diff_summary`+`test_results` from build-report and `proposed_tasks`+`acceptance_criteria` from scout-report; triage reads `proposed_tasks` only. Promoted to default=1 in cycle 24 (v9.4.0). Set `EVOLVE_ANCHOR_EXTRACT=0` to revert to legacy full-file mode. [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_ANTHROPIC_BASE_URL", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ARTIFACT_MAX_EXTENDS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ARTIFACT_TIMEOUT_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_AUDITOR_CLI", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_AUDITOR_INTERACTIVE_POLICY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_AUDITOR_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_AUDITOR_TIER_OVERRIDE", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Override auditor model tier"},
	{Name: "EVOLVE_AUDIT_INTERACTIVE_POLICY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_AUDIT_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_AUDIT_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_AUTO_PRUNE", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Enable auto-prune of expired state entries"},
	{Name: "EVOLVE_AUTO_RESUME_MAX_ATTEMPTS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BACKFILL_ENABLED", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BASH_PARITY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BATCH_BUDGET_CAP", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (token-budget cost gates removed; cost calculation was unreliable across LLM models). Accepted but ignored."},
	{Name: "EVOLVE_BATCH_BUDGET_DISABLE", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (batch budget tripwire removed with the token-budget cost gates). Accepted but ignored."},
	{Name: "EVOLVE_BRIDGE_CATALOG_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BRIDGE_GO", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BRIDGE_INTEGRATION_LIVE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BRIDGE_LIVE_CLI", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BRIDGE_LIVE_CLI_INTERACTIVE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BRIDGE_LIVE_CLI_ROUNDTRIP", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BRIDGE_MANIFEST_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BRIDGE_PIDFILE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BRIDGE_RECIPE_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUDGET_CAP", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (deprecation bridge removed with the token-budget cost gates). Accepted but ignored."},
	{Name: "EVOLVE_BUDGET_ENFORCE", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (budget enforcement removed with the token-budget cost gates). Accepted but ignored."},
	{Name: "EVOLVE_BUDGET_MAX_CYCLES", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op: --budget-usd no longer drives cycle count (token-budget removal). Use --cycles N. Accepted but ignored."},
	{Name: "EVOLVE_BUILD", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILDER_COST_GUARD_STRICT", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (builder cost guard removed with the token-budget cost gates). Accepted but ignored."},
	{Name: "EVOLVE_BUILDER_COST_THRESHOLD", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (builder cost guard removed with the token-budget cost gates). Accepted but ignored."},
	{Name: "EVOLVE_BUILDER_INTERACTIVE_POLICY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILDER_ISOLATION_STRICT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILDER_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILDER_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILDER_REVIEW_SKILLS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILDER_REVIEW_THRESHOLD", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILDER_SELF_REVIEW", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILDER_WORKTREE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILD_CLI", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILD_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILD_PERMISSION_MODE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILD_PLANNER", Status: StatusActive, Cluster: "Budget Cluster", Doc: "Opt C build-planner phase. `1` = advisory (default; build-plan.md produced, Builder reads it as a sanity check); `0` = opt-out. Enforce mode in cycle-105 (Builder Step 3 removed). 3-cycle rollout: shadow→advisory→enforce. Revert: `EVOLVE_BUILD_PLANNER=0`. See ADR-0019."},
	{Name: "EVOLVE_BUILD_PLANNER_LATENCY_CEILING_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BUILD_PLANNER_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILD_PLAN_INPUT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILD_PLAN_OUTPUT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BUILD_SYSTEM_PROMPT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_BYPASS_COMMIT_GATE", Status: StatusActive, Cluster: "Bypass / Emergency Hatches", Doc: "Emergency hatch: skip the `--class manual` commit-gate review attestation (`.commit-gate/attestation.json`). Routine use is a CLAUDE.md violation. `--dry-run` is exempt by construction. Reader: `go/internal/phases/ship/commitgate.go`"},
	{Name: "EVOLVE_BYPASS_PHASE_GATE", Status: StatusActive, Cluster: "Bypass / Emergency Hatches", Doc: "Emergency hatch: bypass phase-gate-precondition"},
	{Name: "EVOLVE_BYPASS_POSTEDIT_VALIDATE", Status: StatusActive, Cluster: "Bypass / Emergency Hatches", Doc: "Emergency hatch: bypass postedit validation"},
	{Name: "EVOLVE_BYPASS_PREFIX_GATE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_BYPASS_ROLE_GATE", Status: StatusActive, Cluster: "Bypass / Emergency Hatches", Doc: "Emergency hatch: bypass role-gate"},
	{Name: "EVOLVE_BYPASS_SHIP_GATE", Status: StatusActive, Cluster: "Bypass / Emergency Hatches", Doc: "Emergency hatch: bypass ship-gate"},
	{Name: "EVOLVE_BYPASS_SHIP_VERIFY", Status: StatusDeprecated, Cluster: "Bypass / Emergency Hatches", Doc: "Emits deprecation WARN.", ReplacedBy: "evolve ship --class manual"},
	{Name: "EVOLVE_CACHE_PREFIX_V2", Status: StatusActive, Cluster: "Observability / Prompt Tuning", Doc: "v8.61.0 Campaign A — static-first / dynamic-last prompt layering. When `1`: (Cycle A1) subagent-run.sh emits a small INVOCATION CONTEXT user prompt; (Cycle A2) claude.sh attaches the role-specific bedrock from `build-invocation-context.sh` via `--append-system-prompt` AND adds `--exclude-dynamic-system-prompt-sections` so per-machine sections move out of the cached system layer. Promoted to default=1 in cycle 43 (v10.6+), overdue since v8.62 target. Set `EVOLVE_CACHE_PREFIX_V2=0` to revert to legacy v1 ordering."},
	{Name: "EVOLVE_CARRYOVER_TODO_MAX_UNPICKED", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "Carryover todos threshold [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_CHANNEL", Status: StatusDeprecated, Cluster: "Bridge / Channel", Doc: "Folded into channel.Enabled (ADR-0045 I6); honored via bridge with WARN.", ReplacedBy: "EVOLVE_PHASE_RECOVERY dial family", RemoveIn: "v18.x (one release after I6)"},
	{Name: "EVOLVE_CHECKPOINT_AT_PCT", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op: the cost-percentage checkpoint trigger was removed with the token-budget cost gates. Accepted but ignored."},
	{Name: "EVOLVE_CHECKPOINT_DISABLE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CHECKPOINT_REASON", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CHECKPOINT_REQUEST", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CHECKPOINT_TRIGGERED", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_CHECKPOINT_WARN_AT_PCT", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op: the cost-percentage checkpoint WARN was removed with the token-budget cost gates. Accepted but ignored."},
	{Name: "EVOLVE_CLI", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CLI_HEALTH", Status: StatusActive, Cluster: "Readiness Gate (pre-batch)", Doc: "The one dial for the CLI-health bench layer (cycle-283: a quota-walled codex re-burned its boot on every dispatch all night because nothing remembered the wall). `0` disables ALL of it: the runner's bench-writer (exit-85 + classified `rate_limit` escalation → bench the CLI FAMILY in `.evolve/cli-health.json`, `benched_until` from the wall's own reset hint else a strike-doubled cooldown), the dispatch-chain demotion (benched families start at their fallback; bench is advice — all-benched dispatches least-recently-benched with a loud WARN; policy pins bypass entirely), the loop's per-cycle canary (one `bridge.LiveSmokeTest` per EXPIRED bench: recovered → cleared, walled again → strikes+1), and the advisor's environmental \"CLI health\" prompt section. Preflight's `cli-health` check (WARN-only) and `evolve doctor live <driver>` (the probe that can SEE a quota wall — boot smoke cannot, walls appear only after work is submitted) remain readable surfaces."},
	{Name: "EVOLVE_CODEX_CLAUDE_PATH", Status: StatusDead, Cluster: "Platform / CLI Hybrid", Doc: "Codex hybrid: claude binary path [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_CODEX_CONFIG_PATH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CODEX_REQUIRE_FULL", Status: StatusActive, Cluster: "Platform / CLI Hybrid", Doc: "Require Codex full-mode"},
	{Name: "EVOLVE_CODEX_VERSION_PATH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_COMMIT_EVIDENCE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_COMPACT_PROMPTS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_COMPOSE_PHASES", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CONDITIONAL_MANDATORY", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "`phase:expr` conditional-mandatory predicate; op ∈ `!= == >= <= > <`"},
	{Name: "EVOLVE_CONSENSUS_AUDIT", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Enable consensus-dispatch for auditor"},
	{Name: "EVOLVE_CONTEXT_DIGEST", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "v8.62.0 Campaign B (Tier 2 — digest layer). When `1`, role-context-builder.sh: (B1) lazy-builds `cycle-digest.json` via `build-cycle-digest.sh`; (B2) replaces full intent.md cat with a compact `## Intent (compact)` block (intent_anchor + acceptance_criteria from digest) for scout/triage/plan-review/tdd/builder phases — auditor + retrospective still get the full file. Real-world reduction: scout 84%, triage 40%, builder 43%. Promoted to default=1 in cycle 24 (v9.4.0). Set `EVOLVE_CONTEXT_DIGEST=0` to revert to legacy full-file mode. [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_CONTEXT_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_CONTRACT_CORRECTION_RETRIES", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_CONTRACT_GATE", Status: StatusActive, Kind: "enum", Default: "enforce", Cluster: "Gates", Doc: "Deliverable-contract gate (ADR-0034): off|shadow|enforce, circuit breaker demotes after 3 consecutive blocks."},
	{Name: "EVOLVE_CYCLE_STATE_FILE", Status: StatusDead, Cluster: "Core Infrastructure (never consolidate)", Doc: "Override cycle-state.json path (test seam) [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_DIFF_COMPLEXITY_DISABLE", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Disable diff-complexity check in auditor"},
	{Name: "EVOLVE_DIR", Status: StatusDead, Cluster: "Override / Test Seams", Doc: "Derived `.evolve/` path in phase-gate.sh (internal) [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_DIR_OVERRIDE", Status: StatusDead, Cluster: "Dead Flags (remove from docs; no production reader)", Doc: "Leave in test; document as test-only [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_DISABLE_AUTO_RETROSPECTIVE", Status: StatusDeprecated, Cluster: "Workflow Defaults", Doc: "Superseded by `policy.json:failure_floor` (ADR-0039) which wins when both set; honored one more release with a `deprecated-flag` WARN; removal target next release"},
	{Name: "EVOLVE_DISABLE_WORKSPACE_GUARD", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_DISPATCH_DEPTH", Status: StatusInternal, Doc: "Bridge-recursion depth (B2): set on each fan-out worker command (parent+1), read at the subagent run / dispatch-parallel chokepoint to enforce the recursion cap (max 3). Absent ⇒ 0 (top-level)."},
	{Name: "EVOLVE_DISPATCH_LOG_TTL_DAYS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_DISPATCH_PLAN_LOG", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_DISPATCH_POLICY", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Dispatch verification policy: `off` (skip check) / `verify` (default) / `stop` (fail-fast)"},
	{Name: "EVOLVE_DISPATCH_REPEAT_THRESHOLD", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Threshold for repeat-cycle detection"},
	{Name: "EVOLVE_DISPATCH_STOP_ON_FAIL", Status: StatusDeprecated, Cluster: "Workflow Defaults", Doc: "Bridged to `EVOLVE_DISPATCH_POLICY=stop`; emits stderr WARN; removal target v8.61+"},
	{Name: "EVOLVE_DISPATCH_VERIFY", Status: StatusDeprecated, Cluster: "Workflow Defaults", Doc: "Bridged to `EVOLVE_DISPATCH_POLICY=off` (when `=0`); emits stderr WARN; removal target v8.61+"},
	{Name: "EVOLVE_DOCS_CONTRACT_STRICT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_DRY_RUN_PROVISION_WORKTREE", Status: StatusDead, Cluster: "Worktree / Workspace", Doc: "Dry-run worktree provisioning [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_DYNAMIC_ROUTING", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "Rollout stage: `off`/`0` (static state machine drives — operator escape hatch) / `shadow` (router computes + logs, static drives) / `advisory` (router drives optional surface, spine static; DEFAULT) / `enforce` (router drives, kernel-clamped). Unknown value → `off` + WARN"},
	{Name: "EVOLVE_E2E_ADVISOR_MODEL_CLAUDE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_ADVISOR_MODEL_OLLAMA", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_ADVISOR", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_BUDGET_USD", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_LLM", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_MATRIX", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_MODEL_OLLAMA", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_RETRIES", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_SMOKE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_SMOKE_TIMEOUT_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_SOAK", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_TIMEOUT_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_LIVE_TMUX_TIMEOUT_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_TMUX_LIVE_TIMEOUT_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_E2E_TMUX_TIMEOUT_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_EVAL_GATE", Status: StatusActive, Kind: "enum", Default: "enforce", Cluster: "Gates", Doc: "Structural eval gates (internal/evalgate): off|shadow|enforce. Gate A scout eval materialization, Gate B tdd predicate quality, Gate C floor binding (R9.3)."},
	{Name: "EVOLVE_FAILURE_CLASSIFICATIONS_LOADED", Status: StatusDead, Cluster: "Core Infrastructure (never consolidate)", Doc: "Idempotency guard for failure-classifications.sh [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_FANOUT_AUDITOR", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Enable fan-out for auditor phase (orchestrator picks `dispatch-parallel auditor`; reads `auditor.json:parallel_subtasks[]`)"},
	{Name: "EVOLVE_FANOUT_CACHE_PREFIX", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Write shared cache-prefix.md for siblings"},
	{Name: "EVOLVE_FANOUT_CACHE_PREFIX_FILE", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Path for cache-prefix.md"},
	{Name: "EVOLVE_FANOUT_CANCEL_ON_CONSENSUS", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Cancel remaining workers on K-agreement"},
	{Name: "EVOLVE_FANOUT_CONCURRENCY", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Max parallel workers in flight (default 2)"},
	{Name: "EVOLVE_FANOUT_CONSENSUS_K", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Consensus threshold K"},
	{Name: "EVOLVE_FANOUT_CONSENSUS_POLL_S", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Consensus poll interval"},
	{Name: "EVOLVE_FANOUT_CYCLE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FANOUT_ENABLED", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Master switch for fan-out"},
	{Name: "EVOLVE_FANOUT_PARENT_AGENT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FANOUT_PER_WORKER_BUDGET_USD", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op (per-worker cost cap removed with the token-budget cost gates; fanout no longer reads or injects it). Accepted but ignored."},
	{Name: "EVOLVE_FANOUT_RETROSPECTIVE", Status: StatusDead, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Enable fan-out for retrospective phase [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_FANOUT_SCOUT", Status: StatusDead, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Enable fan-out for scout phase [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_FANOUT_TEST_EXECUTOR", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Escape hatch: override the fanout worker command to bypass the LLM in test harnesses (read in production code, not test-only)"},
	{Name: "EVOLVE_FANOUT_TIMEOUT", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Per-worker timeout in fanout"},
	{Name: "EVOLVE_FANOUT_TRACK_WORKERS", Status: StatusActive, Cluster: "Fan-out Cluster (intentionally separate — do not consolidate per-phase flags)", Doc: "Track active fanout worker PIDs"},
	{Name: "EVOLVE_FANOUT_WORKER_ARTIFACT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FANOUT_WORKER_NAME", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FANOUT_WORKER_TOKEN", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FANOUT_WORKSPACE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FLEET", Status: StatusActive, Kind: "bool", Default: "0", Cluster: "Fleet Cluster (Track C concurrency)", Doc: "Fleet mode (CB.2+): bridges refuse the process-cwd fallback when no worktree is designated (typed ExitBadFlags, never CLI-fallback). Set by the `evolve fleet` supervisor (CE.2); single-driver runs leave it unset and keep the loud-WARN fallback."},
	{Name: "EVOLVE_FORCE_BARE", Status: StatusDead, Cluster: "Platform / CLI Hybrid", Doc: "Force bare API mode (no subscription) [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_FORCE_FRESH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_FORCE_INNER_SANDBOX", Status: StatusDead, Cluster: "Sandbox Cluster", Doc: "Bridged to `EVOLVE_INNER_SANDBOX=1` (v8.60+); emits stderr WARN; removal target v8.61+ [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_GC", Status: StatusActive, Kind: "enum", Default: "off", Cluster: "GC / Retention", Doc: "GC shadow stage (L3.4). off=disabled (default); shadow=discover+plan+log manifest to workspace without mutations; enforce=shadow+apply (opt-in; honors quarantine/ledger/live hard rules)."},
	{Name: "EVOLVE_GEMINI_CLAUDE_PATH", Status: StatusDead, Cluster: "Platform / CLI Hybrid", Doc: "Gemini hybrid: claude binary path [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_GEMINI_REQUIRE_FULL", Status: StatusDead, Cluster: "Platform / CLI Hybrid", Doc: "Require Gemini full-mode (not degraded) [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_GO_BIN", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_GO_BIN_TEST", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_GUARDS_LOG", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_HANG_CLASSIFIER", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INACTIVITY_DISABLE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INACTIVITY_GRACE_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INACTIVITY_POLL_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INACTIVITY_THRESHOLD_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INACTIVITY_WARN_PCT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INNER_SANDBOX", Status: StatusDead, Cluster: "Sandbox Cluster", Doc: "Tri-state inner sandbox: `1`=force-enable, `0`=force-disable, unset=auto from environment.json [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_INSTINCT_SUMMARY_CAP", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "Max instinct summaries in state.json [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_INTENT_DELTA", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_INTENT_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_INTENT_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_INTERACTIVE_POLICY", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_KB_SEARCH_PATHS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_LEDGER_OVERRIDE", Status: StatusActive, Cluster: "Override / Test Seams", Doc: "Override ledger.jsonl path"},
	{Name: "EVOLVE_LOOP_MAX_CONSECUTIVE_FAILS", Status: StatusActive, Kind: "int", Default: "1", Cluster: "Workflow Defaults", Doc: "Consecutive verdict-FAIL cycles a batch absorbs before stopping (default 1 = stop on first FAIL). A PASS/SHIPPED resets the streak; the cap still halts a broken run. rc=3 when any FAIL was absorbed."},
	{Name: "EVOLVE_MANDATORY_PHASES", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "CSV ordered mandatory spine. Omitting `audit` or `ship` emits a `weak-spine` WARN"},
	{Name: "EVOLVE_MARKETPLACE_DIR", Status: StatusActive, Cluster: "Observability / Prompt Tuning", Doc: "Override marketplace dir (test/release seam)"},
	{Name: "EVOLVE_MAX_BUDGET_USD", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op: the adapters no longer resolve or enforce a cost cap (token-budget cost gates removed); claude.sh always passes an unlimited --max-budget-usd sentinel. Accepted but ignored."},
	{Name: "EVOLVE_MAX_OPTIONAL_INSERTIONS", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "Cap on optional phases the router may insert"},
	{Name: "EVOLVE_MODELCATALOG_AUTOREFRESH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_MODELCATALOG_CLASSIFIER_CLI", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_MODEL_CATALOG_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_NAMELESS", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_NATIVE_SHIP", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_NO_EQUALS", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_OBSERVER_AUTOSPAWN", Status: StatusActive, Kind: "bool", Default: "1", Cluster: "Observer", Doc: "Auto-spawn the per-phase observer goroutine (ADR-0030); 0 opts out."},
	{Name: "EVOLVE_OBSERVER_ENABLED", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_ENFORCE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_EOF_GRACE_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_NUDGE_BODY", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_NUDGE_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_POLL_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_STALL_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_OBSERVER_TEST_KEY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_OLLAMA_BASE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PASS_CONFIDENCE_THRESHOLD", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PERSONA_OVERRIDE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_BUILD_BIN", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_COST_CEILING", Status: StatusDead, Cluster: "Budget Cluster", Doc: "DEPRECATED no-op: the cyclehealth cost_envelope anomaly was removed with the token-budget cost gates. Accepted but ignored."},
	{Name: "EVOLVE_PHASE_IO", Status: StatusActive, Cluster: "Phase I/O (ADR-0050)", Doc: "ADR-0050 Phase-3 unified-phase-I/O rollout dial. FULL off→shadow→advisory→enforce ladder (4-value, unlike the 3-value gate dials). off = dormant legacy dispatch, byte-identical (the rollback escape hatch); shadow = typed envelope assembled + compared against legacy disk reads (mismatch → ledger phaseio_shadow_mismatch); advisory = envelope populated + read alongside legacy (legacy still wins); enforce = the typed envelope is AUTHORITATIVE — phase readers consume it and the audit/ship verdict parse is sentinel-mandatory. DEFAULT enforce as of the 3.10 cutover (was off through 18.14.0); set EVOLVE_PHASE_IO=off to roll back. A typo falls back to off (fail-safe, never leaves the dial in an unintended state)."},
	{Name: "EVOLVE_PHASE_LATENCY_CEILING", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_LATENCY_CEILING_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_MAX_ATTEMPTS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_RECOVERY", Status: StatusActive, Cluster: "Phase Recovery (ADR-0044, Go-native — one dial for the whole program)", Doc: "The one dial for BOTH the ADR-0044 phase-recovery program (terminal-state recovery) AND the ADR-0045 corrective-interaction program (repair a live/just-completed phase through bounded interaction). ADR-0044: fatal-pane fast-fail at the stop-review checkpoint, the observer's chain-backed StallPolicy (subprocess injects it ONLY at explicit `enforce`), and the orchestrator's escalate→advise→promote hook (`config.RolloutStages.PhaseRecovery` view). ADR-0045 corrective ACTIONS ride the SAME stage: the graduated correction ladder (salvage→live-fix→re-dispatch), the pre-85 AskBroker rung, promoted-rule enforcement, and the live bidirectional channel (ADR-0037, folded in at I6 — `enforce` implies the channel; `EVOLVE_CHANNEL` deprecated, see below). **Telemetry is EXEMPT**: ADR-0045 I1 interaction telemetry (`<phase>-interactions.ndjson` + `interaction-summary.json`) records at EVERY stage including `off` — only ACTIONS gate. Stages: `off` (detectors not consulted, no corrective actions; byte-identical legacy — telemetry still records) / `shadow` (DEFAULT — detect + log the would-act for every rung, legacy behavior decides; byte-identical) / `enforce` (fatal-pane preempt with `stop`; salvage relocates a misplaced deliverable; the kernel answers a blocking question pre-85; promoted enforce-stage rules fire; exit 81 hands the phase to the runner's CLI fallback chain). Unknown value → `off` (a typo never enables a kill-path). A Busy pane is never preempted/interrupted regardless of stage"},
	{Name: "EVOLVE_PHASE_ROOTS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PHASE_SCOUT_BIN", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_PLAN_REVIEW", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Enable Sprint 2 plan-review phase (opt-in)"},
	{Name: "EVOLVE_PLAN_REVIEWER_INTERACTIVE_POLICY", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_PLAN_REVIEWER_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_PLAN_WORKSPACE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PLATFORM", Status: StatusActive, Cluster: "Platform / CLI Hybrid", Doc: "Override platform detection"},
	{Name: "EVOLVE_PLUGIN_ROOT", Status: StatusActive, Cluster: "Core Infrastructure (never consolidate)", Doc: "Read-only plugin install location"},
	{Name: "EVOLVE_POLICY_BYPASS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PROFILES_DIR_OVERRIDE", Status: StatusActive, Cluster: "Override / Test Seams", Doc: "Override profiles dir path"},
	{Name: "EVOLVE_PROFILE_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PROFILE_OVERRIDE", Status: StatusDead, Cluster: "Override / Test Seams", Doc: "Override pre-built profile path [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_PROFILE_WORKTREE_AWARE", Status: StatusDead, Cluster: "Worktree / Workspace", Doc: "Mark profile as worktree-aware [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_PROJECT_ROOT", Status: StatusActive, Cluster: "Core Infrastructure (never consolidate)", Doc: "Writable project directory (dual-root pattern)"},
	{Name: "EVOLVE_PROMPTS_DIR", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_PROMPT_BUDGET_ENFORCE", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "Make prompt-over-cap a hard error [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_PROMPT_MAX_TOKENS", Status: StatusActive, Cluster: "Observability / Prompt Tuning", Doc: "Soft prompt token cap for role-context-builder"},
	{Name: "EVOLVE_PSMAS_SKIP", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_QUOTA_DANGER_PCT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_QUOTA_RESET_AT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_QUOTA_RESET_HOURS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_REFLECTION_JOURNAL", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_REINVOKE_CMD", Status: StatusDead, Cluster: "Observability / Prompt Tuning", Doc: "Stored reinvoke command for rate-limit recovery [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_RELEASE_REQUIRE_PREFLIGHT", Status: StatusActive, Cluster: "Observability / Prompt Tuning", Doc: "Force release preflight gate"},
	{Name: "EVOLVE_RELEASE_STRICT_PASS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_REQUIRE_INTENT", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Force intent phase on every cycle"},
	{Name: "EVOLVE_REQUIRE_TEAM_CONTEXT", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Require team context before builder"},
	{Name: "EVOLVE_RESEARCH_CACHE_ENABLED", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESEARCH_HOOK_DISABLED", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_RESET", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESOLVE_ROOTS_LOADED", Status: StatusDead, Cluster: "Core Infrastructure (never consolidate)", Doc: "Idempotency guard for resolve-roots.sh sourcing [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_RESUME", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESUME_ALLOW_HEAD_MOVED", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESUME_COMPLETED_PHASES", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESUME_MODE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RESUME_PHASE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RETROSPECTIVE_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_RETRO_MODEL", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_RETRY_BACKOFF_BASE_S", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_REVIEW_GATE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ROUTER_CLI", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ROUTER_MODEL", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_ROUTING_MODE", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "Routing brain: `llm`/`dynamic`/`dynamic-llm` (LLM proposes, kernel clamps) / `static`/`static-preset`/`preset` (triggers + spine only, no LLM). Unknown → `llm` + WARN"},
	{Name: "EVOLVE_RUN_TIMEOUT", Status: StatusActive, Cluster: "Observability / Prompt Tuning", Doc: "Per-subagent run timeout"},
	{Name: "EVOLVE_SANDBOX", Status: StatusActive, Cluster: "Sandbox Cluster", Doc: "Enable outer sandbox-exec/bwrap wrapper"},
	{Name: "EVOLVE_SANDBOX_FALLBACK_ON_EPERM", Status: StatusActive, Cluster: "Sandbox Cluster", Doc: "EPERM fallback for nested-Claude (Darwin 25.4+)"},
	{Name: "EVOLVE_SCOUT_CLI", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_SCOUT_INTERACTIVE_POLICY", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SCOUT_LATENCY_CEILING_S", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_SCOUT_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_SCOUT_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_SCROLLBACK_LINES", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SHIP_AUTO_CONFIRM", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "CI mode: skip interactive y/N in ship.sh"},
	{Name: "EVOLVE_SHIP_RELEASE_NOTES", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Create GitHub release on ship"},
	{Name: "EVOLVE_SHIP_SCRIPT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SKIP_CYCLE_HEALTH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SKIP_PREFLIGHT", Status: StatusActive, Cluster: "Readiness Gate (pre-batch)", Doc: "Emergency hatch: skip the whole readiness gate (no checks, no boot)"},
	{Name: "EVOLVE_SKIP_PREFLIGHT_BOOT", Status: StatusActive, Cluster: "Readiness Gate (pre-batch)", Doc: "Run the cheap checks (structure/CLI/host) but skip the real bridge-boot probe — CI/offline (bridge-boot downgrades Halt→Warn)"},
	{Name: "EVOLVE_SKIP_WORKTREE", Status: StatusActive, Cluster: "Worktree / Workspace", Doc: "Emergency hatch: skip per-cycle worktree isolation"},
	{Name: "EVOLVE_STATE_FILE_OVERRIDE", Status: StatusDead, Cluster: "State File Cluster (cycle 7 consolidation)", Doc: "Override state.json path [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_STATE_OVERRIDE", Status: StatusDead, Cluster: "State File Cluster (cycle 7 consolidation)", Doc: "Alias for `EVOLVE_STATE_FILE_OVERRIDE`; emits stderr WARN [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_STDOUT_FILTER", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_STRATEGY", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Cycle strategy override"},
	{Name: "EVOLVE_STRICT_AUDIT", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "WARN→FAIL promotion in ship.sh + failure-adapter blocking (v8.35+); single severity gate"},
	{Name: "EVOLVE_STRICT_FAILURES", Status: StatusDead, Cluster: "Workflow Defaults", Doc: "Bridged to `EVOLVE_STRICT_AUDIT`; emits stderr WARN; removal target v8.61+ [no reader on any surface as of 2026-06-11 inventory]"},
	{Name: "EVOLVE_SWARM_CONCURRENCY", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SWARM_PLANNER", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SWARM_PORT_BASE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SWARM_STAGE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_SYSTEM_PROMPT", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TASK_MODE", Status: StatusActive, Cluster: "Workflow Defaults", Doc: "Profile tier selector (default/research/deep)"},
	{Name: "EVOLVE_TDD_ENGINEER_CLI", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TDD_ENGINEER_INTERACTIVE_POLICY", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TDD_ENGINEER_MODEL", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TDD_ENGINEER_PERMISSION_MODE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TDD_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TDD_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TDD_PHASE", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TDD_PHASE_N", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TDD_PLAN_INPUT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TESTING", Status: StatusActive, Cluster: "Core Infrastructure (never consolidate)", Doc: "Test harness mode — disables real CLI calls"},
	{Name: "EVOLVE_TEST_COST_GUARD_STRICT", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TEST_COST_THRESHOLD", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TEST_PHASE_ENABLED", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TRACKER_TTL_DAYS", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_TRIAGE_AUTO_SKIP_TRIVIAL", Status: StatusActive, Cluster: "Triage Cluster (cycle 7 trim)", Doc: "Opt A: auto-skip Triage when 3 conditions hold (≤1 scout task AND empty carryoverTodos AND predicate-dependency-check.sh exit 0). Default on (=1); opt-out with =0. Writes a stub `triage-decision.{md,json}` with `auto_skip: true` so downstream phases see consistent inputs."},
	{Name: "EVOLVE_TRIAGE_CAP_GATE", Status: StatusActive, Kind: "enum", Default: "enforce", Cluster: "Gates", Doc: "R9.2 triage capacity clamp: off|shadow|enforce. Committed coverage floors above ceil(1.25\u00b7K observed throughput) reject triage into the correction ladder."},
	{Name: "EVOLVE_TRIAGE_DISABLE", Status: StatusActive, Cluster: "Triage Cluster (cycle 7 trim)", Doc: "Opt-out of triage default-on (v8.59+)"},
	{Name: "EVOLVE_TRIAGE_ENABLED", Status: StatusDead, Cluster: "Triage Cluster (cycle 7 trim)", Doc: "v8.56–v8.58 opt-in; replaced by `EVOLVE_TRIAGE_DISABLE`; removed from docs"},
	{Name: "EVOLVE_TRIAGE_MODEL", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TRIAGE_PERMISSION_MODE", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
	{Name: "EVOLVE_TRIAGE_TOP_N", Status: StatusActive, Cluster: "Triage Cluster (cycle 7 trim)", Doc: "Override triage top_n selection count"},
	{Name: "EVOLVE_USE_LEGACY_BASH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_USE_PHASE_REGISTRY", Status: StatusActive, Cluster: "Dynamic Phase Routing (Go-native, v13.0.0 / PR #4 — default-off)", Doc: "Set `0` to skip reading `phase-registry.json` (built-in defaults only)"},
	{Name: "EVOLVE_WORKTREE_BASE", Status: StatusActive, Cluster: "Worktree / Workspace", Doc: "Per-cycle worktree base path"},
	{Name: "EVOLVE_WORKTREE_PATH", Status: StatusInternal, Doc: "Undocumented production reader (inventory 2026-06-11); classify when touched."},
	{Name: "EVOLVE_X", Status: StatusTestSeam, Doc: "Read only by _test.go files."},
}
