package phasecoherence

import (
	"errors"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"testing"
)

func TestNoRuntimeArtifactsTracked(t *testing.T) {
	t.Parallel()
	root := repoRootForPairing(t)

	// Every rule names its production writer: a rule nobody can trace is one nobody can safely delete.
	rules := []struct {
		re   *regexp.Regexp
		why  string
		rule string // the .gitignore line governing new births of this class
	}{
		{
			re:   regexp.MustCompile(`\.log$`),
			why:  "run log (loop/release/bridge stdout capture)",
			rule: "/*.log",
		},
		{
			re:   regexp.MustCompile(`(^|/)coverage\.[^/]*\.txt$`),
			why:  "ACS coverage output — `go test -coverprofile=` + `go tool cover -func` inside go/acs/cycle*/predicates_test.go regenerate it",
			rule: "coverage.*.txt",
		},
		{
			re:   regexp.MustCompile(`(^|/)tmux-sessions\.jsonl$`),
			why:  "per-workspace tmux session registry — sessionrecord.FileName",
			rule: "/tmux-sessions.jsonl",
		},
		{
			re:   regexp.MustCompile(`(^|/)model-classifier-`),
			why:  "model-classifier probe artifact — cmd_models_live.go writes it to the agent workspace",
			rule: "/model-classifier-*",
		},
		{
			re:   regexp.MustCompile(`^lint-baseline\.txt$`),
			why:  "lint-tool baseline snapshot at the repo root — no production writer identified; operator/tool-generated",
			rule: "/lint-baseline.txt",
		},
		{
			re:   regexp.MustCompile(`(^|/)\.bridge-inbox/`),
			why:  "bridge inject scratch — bridge/tmux_inject.go writes <workspace>/.bridge-inbox/<agent>-inject.txt",
			rule: ".bridge-inbox/",
		},
		{
			// The leading slash matches only a nested .evolve/; the root corpus ships by design.
			re:   regexp.MustCompile(`/\.evolve/`),
			why:  "nested .evolve/ runtime state created in a phase's cwd",
			rule: "*/**/.evolve/",
		},
	}

	allowed := map[string]string{
		"go/internal/logfilter/testdata/streamjson-input.log": "test fixture: the recorded stream-json the logfilter tests parse, not a run log",
	}

	out, err := exec.Command("git", "-C", root, "ls-files").Output()
	if err != nil {
		// ExitError.Error() is only "exit status N"; git's reason is on stderr.
		var ee *exec.ExitError
		if errors.As(err, &ee) && len(ee.Stderr) > 0 {
			t.Fatalf("git ls-files: %v: %s", err, ee.Stderr)
		}
		t.Fatalf("git ls-files: %v", err)
	}
	tracked := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(tracked) < 100 {
		t.Fatalf("git ls-files returned only %d paths — the probe itself is broken", len(tracked))
	}

	var violations []string
	usedAllowance := map[string]bool{}
	for _, p := range tracked {
		if p == "" {
			continue
		}
		for _, r := range rules {
			if !r.re.MatchString(p) {
				continue
			}
			if _, ok := allowed[p]; ok {
				usedAllowance[p] = true
				break
			}
			violations = append(violations, p+"\n      class: "+r.why+
				"\n      fix:   git rm --cached "+p+"   (ignore ladder: "+r.rule+")")
			break
		}
	}

	if len(violations) > 0 {
		sort.Strings(violations)
		t.Errorf("%d runtime artifact(s) are tracked — the upstream tree must hold only code and docs.\n"+
			"These are regenerated by the pipeline and ship to every clone:\n\n  - %s\n\n"+
			"If one of these is genuine repo content, add it to `allowed` in this file WITH its reason.",
			len(violations), strings.Join(violations, "\n  - "))
	}

	for p := range allowed {
		if !usedAllowance[p] {
			t.Errorf("allowlist entry %q no longer matches any tracked artifact path — delete it "+
				"(a stale allowance pre-approves a future regression at that path)", p)
		}
	}
}
