//go:build acs

package cycle1840

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mickeyyaya/evolve-loop/go/internal/skillcheck"
	"github.com/mickeyyaya/evolve-loop/go/pkg/acsassert"
)

const (
	pluginRootVar   = "${CLAUDE_PLUGIN_ROOT}"
	generatedMarker = "<!-- GENERATED by `evolve skills generate` from skills/"
	legacyToolIDTag = "Skill tool id"
)

func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, relErr := filepath.Rel(src, path)
		if relErr != nil {
			return relErr
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !d.Type().IsRegular() {
			return nil
		}
		raw, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if mkErr := os.MkdirAll(filepath.Dir(target), 0o755); mkErr != nil {
			return mkErr
		}
		return os.WriteFile(target, raw, 0o644)
	})
	if err != nil {
		t.Fatalf("copy %s -> %s: %v", src, dst, err)
	}
}

func repoFixture(t *testing.T) string {
	t.Helper()
	root := acsassert.RepoRoot(t)
	fixture := t.TempDir()
	copyTree(t, filepath.Join(root, "docs", "architecture", "phase-registry.json"), filepath.Join(fixture, "docs", "architecture", "phase-registry.json"))
	for _, dir := range []string{"skills", "commands", "agents", filepath.Join(".evolve", "profiles")} {
		copyTree(t, filepath.Join(root, dir), filepath.Join(fixture, dir))
	}
	return fixture
}

func generate(t *testing.T, root string) {
	t.Helper()
	var stderr strings.Builder
	if code := skillcheck.Run(root, true, io.Discard, &stderr); code != 0 {
		t.Fatalf("evolve skills generate exit %d\n%s", code, stderr.String())
	}
}

type generatedCommand struct {
	name, body string
}

func generatedCommands(t *testing.T, root string) []generatedCommand {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(root, "commands"))
	if err != nil {
		t.Fatalf("read commands dir: %v", err)
	}
	var out []generatedCommand
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		raw, readErr := os.ReadFile(filepath.Join(root, "commands", e.Name()))
		if readErr != nil {
			t.Fatalf("read %s: %v", e.Name(), readErr)
		}
		if strings.Contains(string(raw), generatedMarker) {
			out = append(out, generatedCommand{name: strings.TrimSuffix(e.Name(), ".md"), body: string(raw)})
		}
	}
	if len(out) == 0 {
		t.Fatalf("no generated command stubs under %s/commands", root)
	}
	return out
}

func assertNoSelfReference(t *testing.T, cmds []generatedCommand) {
	t.Helper()
	for _, c := range cmds {
		if strings.Contains(c.body, "evo:"+c.name) {
			t.Errorf("commands/%s.md tells the reader to load evo:%s, the id it is itself registered under", c.name, c.name)
		}
		if strings.Contains(c.body, legacyToolIDTag) {
			t.Errorf("commands/%s.md still routes through the Skill tool id", c.name)
		}
	}
}

func assertPluginPathResolves(t *testing.T, root string, cmds []generatedCommand) {
	t.Helper()
	for _, c := range cmds {
		want := pluginRootVar + "/skills/" + c.name + "/SKILL.md"
		if !strings.Contains(c.body, want) {
			t.Errorf("commands/%s.md does not name %s", c.name, want)
			continue
		}
		resolved := filepath.Join(root, "skills", c.name, "SKILL.md")
		if _, err := os.Stat(resolved); err != nil {
			t.Errorf("commands/%s.md names %s but it does not resolve under the plugin root: %v", c.name, want, err)
		}
	}
}

func TestC1840_001_GeneratedCommandNeverLoadsItsOwnID(t *testing.T) {
	fixture := repoFixture(t)
	generate(t, fixture)
	assertNoSelfReference(t, generatedCommands(t, fixture))
}

func TestC1840_002_GeneratedCommandNamesPluginSkillPath(t *testing.T) {
	fixture := repoFixture(t)
	generate(t, fixture)
	assertPluginPathResolves(t, fixture, generatedCommands(t, fixture))
	var stderr strings.Builder
	if code := skillcheck.Run(fixture, false, io.Discard, &stderr); code != 0 {
		t.Errorf("check after generate exit %d, want 0 (idempotent)\n%s", code, stderr.String())
	}
}

func TestC1840_003_RepoCommandsHaveZeroDriftAndNoSelfReference(t *testing.T) {
	root := acsassert.RepoRoot(t)
	drift, err := skillcheck.Check(root)
	if err != nil {
		t.Fatalf("skillcheck.Check: %v", err)
	}
	if len(drift) != 0 {
		t.Errorf("skillcheck.Check reports drift: %v", drift)
	}
	cmds := generatedCommands(t, root)
	assertNoSelfReference(t, cmds)
	assertPluginPathResolves(t, root, cmds)
}

func TestC1840_004_LegacySelfReferencingStubIsDrift(t *testing.T) {
	fixture := repoFixture(t)
	generate(t, fixture)
	stubPath := filepath.Join(fixture, "commands", "loop.md")
	raw, err := os.ReadFile(stubPath)
	if err != nil {
		t.Fatalf("read generated loop stub: %v", err)
	}
	lines := strings.Split(string(raw), "\n")
	instruction := -1
	for i, line := range lines {
		if strings.HasPrefix(line, "Arguments:") {
			instruction = i - 2
		}
	}
	if instruction < 0 {
		t.Fatalf("generated loop stub has no Arguments line:\n%s", raw)
	}
	lines[instruction] = "Run the **loop** skill from the `evo` plugin (Skill tool id `evo:loop`); follow its SKILL.md instructions exactly."
	if err := os.WriteFile(stubPath, []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		t.Fatal(err)
	}
	drift, err := skillcheck.Check(fixture)
	if err != nil {
		t.Fatalf("skillcheck.Check: %v", err)
	}
	for _, d := range drift {
		if d == filepath.Join("commands", "loop.md") {
			return
		}
	}
	t.Errorf("a self-referencing legacy stub must be drift; Check returned %v", drift)
}
