package core

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mickeyyaya/evolve-loop/go/internal/gittest"
)

const commandStub = "commands/build.md"

func commandStubConflictRepo(t *testing.T) *gittest.Repo {
	t.Helper()
	repo := gittest.Fixture(t)
	stub := filepath.Join(repo.Dir, commandStub)
	writeFile(t, stub, "<!-- GENERATED by `evolve skills generate` from skills/build/SKILL.md — DO NOT EDIT. -->\nbase\n")
	repo.Git("add", "-A")
	repo.Git("commit", "-qm", "base")
	repo.Git("checkout", "-qb", "cycle")
	writeFile(t, stub, "<!-- GENERATED by `evolve skills generate` from skills/build/SKILL.md — DO NOT EDIT. -->\nlane\n")
	writeFile(t, filepath.Join(repo.Dir, "skills", "build", "SKILL.md"), "lane skill\n")
	repo.Git("add", "-A")
	repo.Git("commit", "-qm", "lane")
	repo.Git("checkout", "-q", "main")
	writeFile(t, stub, "<!-- GENERATED by `evolve skills generate` from skills/build/SKILL.md — DO NOT EDIT. -->\npeer\n")
	repo.Git("add", "-A")
	repo.Git("commit", "-qm", "peer")
	repo.Git("checkout", "-q", "cycle")
	return repo
}

func TestRebaseWithDerivedRegen_ACommandStubConflictRegenerates(t *testing.T) {
	repo := commandStubConflictRepo(t)
	regenerated := "<!-- GENERATED by `evolve skills generate` from skills/build/SKILL.md — DO NOT EDIT. -->\nregenerated\n"
	var asked []string
	regen := func(_ context.Context, wt, key string) error {
		asked = append(asked, key)
		return os.WriteFile(filepath.Join(wt, commandStub), []byte(regenerated), 0o644)
	}

	ok, conflicts := rebaseWithDerivedRegen(context.Background(), repo.Dir, gitCapture, regen, derivedConflictIn(repo.Dir))

	if !ok || len(conflicts) != 0 {
		t.Fatalf("a conflict only in a generated command stub must regenerate, not go to the debugger: got ok=%v conflicts=%v", ok, conflicts)
	}
	if got, _ := os.ReadFile(filepath.Join(repo.Dir, commandStub)); string(got) != regenerated {
		t.Errorf("%s = %q, want the regenerated stub", commandStub, got)
	}
	if status := repo.Git("status", "--porcelain"); status != "" {
		t.Errorf("worktree after the regenerated rebase = %q, want clean", status)
	}
	if base := repo.Git("merge-base", "main", "cycle"); base != repo.Git("rev-parse", "main") {
		t.Errorf("cycle is not rebased onto main: merge-base %s", base)
	}
	if strings.Join(asked, ",") == "" {
		t.Error("the regenerator never ran")
	}
}

const recordingEvolveMain = `package main

import (
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := os.Getenv("EVOLVE_WORKTREE_ROOT")
	cwd, _ := os.Getwd()
	f, err := os.OpenFile(filepath.Join(root, "generator.log"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		os.Exit(3)
	}
	defer f.Close()
	f.WriteString(cwd + "|" + strings.Join(os.Args[1:], " ") + "\n")
}
`

func recordingWorktree(t *testing.T) *gittest.Repo {
	t.Helper()
	repo := gittest.Fixture(t)
	writeFile(t, filepath.Join(repo.Dir, "go", "go.mod"), "module fakeevolve\n\ngo 1.21\n")
	writeFile(t, filepath.Join(repo.Dir, "go", "cmd", "evolve", "main.go"), recordingEvolveMain)
	writeFile(t, filepath.Join(repo.Dir, "go", "internal", "skillcheck", "s.go"), "package skillcheck\n")
	writeFile(t, filepath.Join(repo.Dir, ".gitignore"), "generator.log\n")
	repo.Git("add", "-A")
	repo.Git("commit", "-qm", "base")
	return repo
}

func TestRegen_UsesTheGeneratorOfTheWorktree(t *testing.T) {
	if testing.Short() {
		t.Skip("compiles the worktree's cmd/evolve via `go run`; skipped under -short")
	}
	repo := recordingWorktree(t)

	err := regenerateDerivedArtifact(context.Background(), repo.Dir, "skill-projections")

	raw, _ := os.ReadFile(filepath.Join(repo.Dir, "generator.log"))
	goDir, _ := filepath.EvalSymlinks(filepath.Join(repo.Dir, "go"))
	want := goDir + "|skills generate\n" + goDir + "|skills check\n"
	if string(raw) != want {
		t.Fatalf("the worktree generator recorded %q, want %q", raw, want)
	}
	if err != nil {
		t.Fatalf("regenerateDerivedArtifact = %v, want nil", err)
	}
}

func TestDerivedConflictIn_ReadsTheMergedFile(t *testing.T) {
	wt := t.TempDir()
	conflict := "<<<<<<< HEAD\na\n=======\nb\n>>>>>>> lane\n"
	writeFile(t, filepath.Join(wt, cflags), "<!-- GENERATED:flag-index BEGIN -->\n"+conflict+"<!-- GENERATED:flag-index END -->\n")
	writeFile(t, filepath.Join(wt, "docs", "architecture", "signal-codes.md"), conflict+"<!-- GENERATED:signal-codes BEGIN -->\n<!-- GENERATED:signal-codes END -->\n")
	classify := derivedConflictIn(wt)
	cases := []struct {
		path, entry string
		ok          bool
	}{
		{cflags, "flag-index", true},
		{"docs/architecture/signal-codes.md", "", false},
		{"commands/deleted.md", "", false},
		{"skills/build/SKILL.md", "", false},
		{"go/internal/core/x.go", "", false},
	}
	for _, c := range cases {
		if entry, ok := classify(c.path); entry != c.entry || ok != c.ok {
			t.Errorf("classify(%q) = (%q, %v), want (%q, %v)", c.path, entry, ok, c.entry, c.ok)
		}
	}
}

func TestRebaseWithDerivedRegen_RegeneratesAnEntryOncePerStep(t *testing.T) {
	g := &scriptedGit{}
	g.respond = func(args []string) (string, int, error) {
		j := joined(args)
		switch {
		case strings.HasPrefix(j, "diff --name-only --diff-filter=U"):
			return "commands/a.md\x00commands/b.md\x00" + cflags + "\x00", 0, nil
		case strings.HasPrefix(j, "ls-files "):
			return "commands/a.md\x00", 0, nil
		case j == "rebase main":
			return "", 1, nil
		}
		return "", 0, nil
	}
	regen, got := recordingRegen("")

	ok, conflicts := rebaseWithDerivedRegen(context.Background(), "/wt", g.capture, regen, derivedEntryOf)

	if !ok || len(conflicts) != 0 {
		t.Fatalf("rebase = (%v, %v), want (true, none)", ok, conflicts)
	}
	if want := "skill-projections,flag-index"; strings.Join(*got, ",") != want {
		t.Fatalf("regenerated = %v, want %s: one run per entry, not one per path", *got, want)
	}
}

func TestStageDerivedEntry_NoOutputOnDiskStagesNothing(t *testing.T) {
	dir, git := initTempRepo(t)
	writeFile(t, filepath.Join(dir, "base.txt"), "base\n")
	git("add", "-A")
	git("commit", "-m", "base")

	if err := stageDerivedEntry(context.Background(), dir, "skill-projections"); err != nil {
		t.Fatalf("stageDerivedEntry with no output on disk = %v, want nil", err)
	}
}

func TestRefreshDerivedEntry_AnUnknownEntryIsAnError(t *testing.T) {
	if err := refreshDerivedEntry(context.Background(), t.TempDir(), "goal-recipes"); err == nil {
		t.Fatal("refreshDerivedEntry(goal-recipes) = nil, want an error")
	}
}

func TestNormalizeDerivedProjections_ChecksAStaleEntryWithTheWorktreeGenerator(t *testing.T) {
	if testing.Short() {
		t.Skip("compiles the worktree's cmd/evolve via `go run`; skipped under -short")
	}
	cases := []struct {
		name, changed, body, want string
	}{
		{"a path input", "skills/build/SKILL.md", "lane skill\n", "skills check"},
		{"a package in the skillcheck closure", "go/internal/skillcheck/s.go", "package skillcheck\n\nvar X = 1\n", "skills check"},
		{"a closure that go list cannot read falls back to the path inputs", "go/internal/skillcheck/s.go", "package skillcheck\n\nimport _ \"fakeevolve/nope\"\n", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			repo := recordingWorktree(t)
			writeFile(t, filepath.Join(repo.Dir, filepath.FromSlash(c.changed)), c.body)

			(&Orchestrator{}).normalizeDerivedProjections(context.Background(), repo.Dir)

			raw, _ := os.ReadFile(filepath.Join(repo.Dir, "generator.log"))
			if got := loggedArgs(string(raw)); got != c.want {
				t.Fatalf("generator calls = %q, want %q", got, c.want)
			}
		})
	}
}

func loggedArgs(log string) string {
	var args []string
	for _, line := range strings.Split(strings.TrimSpace(log), "\n") {
		if _, a, ok := strings.Cut(line, "|"); ok {
			args = append(args, a)
		}
	}
	return strings.Join(args, ";")
}

func TestRebaseCycleBranchOntoMain_AConflictOutsideTheGeneratedRegionGoesToTheDebugger(t *testing.T) {
	dir := initConflictRepo(t, cflags)

	ok, conflicts := rebaseCycleBranchOntoMain(context.Background(), "", dir)

	if ok || strings.Join(conflicts, ",") != cflags {
		t.Fatalf("rebase = (%v, %v), want (false, [%s]): a hand edit outside the generated region is genuine", ok, conflicts, cflags)
	}
}
