#!/usr/bin/env bash
#
# index-investigations.sh — Regenerate INDEX.md for .evolve/audit-investigations/.
#
# Walks subdirs of .evolve/audit-investigations/, parses each subdir's
# status.json + lesson.yaml, produces a chronological table in INDEX.md.
#
# Run manually after any operator-driven status change, or auto-called by
# merge-lesson-into-state.sh after Retrospective produces a new investigation.
#
# Usage:
#   bash scripts/index-investigations.sh                 # regenerate INDEX.md
#   bash scripts/index-investigations.sh --json          # emit JSON instead of markdown
#   bash scripts/index-investigations.sh --check         # exit 0 if INDEX.md is current; 1 if stale
#
# Exit codes:
#   0 — index regenerated (or --check found INDEX.md current)
#   1 — --check found INDEX.md stale
#  10 — bad arguments

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INV_DIR="${EVOLVE_PROJECT_ROOT:-$REPO_ROOT}/.evolve/audit-investigations"
INDEX="$INV_DIR/INDEX.md"

JSON=0
CHECK=0

while [ $# -gt 0 ]; do
    case "$1" in
        --json)  JSON=1 ;;
        --check) CHECK=1 ;;
        --help|-h) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        --*)     echo "[index-investigations] unknown flag: $1" >&2; exit 10 ;;
        *)       echo "[index-investigations] unknown arg: $1" >&2; exit 10 ;;
    esac
    shift
done

[ -d "$INV_DIR" ] || { echo "[index-investigations] no investigations dir at $INV_DIR — creating" >&2; mkdir -p "$INV_DIR"; }

# Collect investigation entries via newline-delimited records.
# Format: date<TAB>cycle<TAB>verdict<TAB>slug<TAB>status<TAB>lesson_id
records=""
for d in "$INV_DIR"/*/; do
    [ -d "$d" ] || continue
    name=$(basename "$d")
    # Parse name: <YYYY-MM-DD>-cycle-<N>-<VERDICT>-<slug>
    if ! [[ "$name" =~ ^([0-9]{4}-[0-9]{2}-[0-9]{2})-cycle-([0-9]+)-(FAIL|WARN|WARN-NO-AUDIT)-(.+)$ ]]; then
        continue
    fi
    date="${BASH_REMATCH[1]}"
    cycle="${BASH_REMATCH[2]}"
    verdict="${BASH_REMATCH[3]}"
    slug="${BASH_REMATCH[4]}"
    # Read status.json if present
    state="?"
    lesson_id="-"
    if [ -f "$d/status.json" ]; then
        state=$(jq -r '.state // "?"' "$d/status.json" 2>/dev/null || echo "?")
        lesson_id=$(jq -r '.lesson_id // "-"' "$d/status.json" 2>/dev/null || echo "-")
    fi
    records="${records}${date}\t${cycle}\t${verdict}\t${slug}\t${state}\t${lesson_id}\n"
done

# Sort by date (descending — most recent first), then cycle (descending)
sorted=$(printf "$records" | sort -k1,1r -k2,2nr -t$'\t')

# Counts by state
count_open=0
count_closed=0
count_implemented=0
total=0
while IFS=$'\t' read -r date cycle verdict slug state lesson_id; do
    [ -z "$date" ] && continue
    total=$((total + 1))
    case "$state" in
        open) count_open=$((count_open + 1)) ;;
        closed) count_closed=$((count_closed + 1)) ;;
        implemented) count_implemented=$((count_implemented + 1)) ;;
    esac
done <<< "$sorted"

if [ "$JSON" = "1" ]; then
    # Emit JSON
    entries_json="["
    first=1
    while IFS=$'\t' read -r date cycle verdict slug state lesson_id; do
        [ -z "$date" ] && continue
        [ "$first" = "0" ] && entries_json+=","
        first=0
        entries_json+=$(jq -nc --arg d "$date" --argjson c "$cycle" --arg v "$verdict" --arg s "$slug" --arg st "$state" --arg l "$lesson_id" \
            '{date:$d, cycle:$c, verdict:$v, slug:$s, state:$st, lesson_id:$l}')
    done <<< "$sorted"
    entries_json+="]"
    jq -nc --argjson entries "$entries_json" --argjson total "$total" \
        --argjson open "$count_open" --argjson closed "$count_closed" --argjson impl "$count_implemented" \
        '{total: $total, by_state: {open: $open, closed: $closed, implemented: $impl}, entries: $entries}'
    exit 0
fi

# Generate markdown INDEX.md
new_index=$(mktemp)
cat > "$new_index" <<EOF
# Audit Investigations Index

> Auto-generated by \`scripts/index-investigations.sh\`. Run after any new investigation is created or status updated.

| Date | Cycle | Verdict | Slug | Status | Lesson |
|---|---|---|---|---|---|
EOF

if [ "$total" = "0" ]; then
    echo "" >> "$new_index"
    echo "(No investigations yet — index will populate as FAIL/WARN cycles complete.)" >> "$new_index"
else
    while IFS=$'\t' read -r date cycle verdict slug state lesson_id; do
        [ -z "$date" ] && continue
        echo "| $date | $cycle | $verdict | [\`$slug\`](${date}-cycle-${cycle}-${verdict}-${slug}/) | $state | $lesson_id |" >> "$new_index"
    done <<< "$sorted"
fi

cat >> "$new_index" <<EOF

## Counts

| State | Count |
|---|---|
| open | $count_open |
| closed | $count_closed |
| implemented | $count_implemented |
| **total** | **$total** |

## How to use

See [README.md](README.md) for the full workflow. Quick reference:

- Open the dir matching the date+cycle+verdict you want to inspect
- Read \`investigation.md\` for the narrative
- Read \`improvements.md\` for proposed fixes
- Update \`status.json\` after you decide / action
- Run \`bash scripts/index-investigations.sh\` to refresh this index
EOF

if [ "$CHECK" = "1" ]; then
    if [ -f "$INDEX" ] && diff -q "$new_index" "$INDEX" >/dev/null 2>&1; then
        rm -f "$new_index"
        echo "[index-investigations] INDEX.md is current"
        exit 0
    else
        rm -f "$new_index"
        echo "[index-investigations] INDEX.md is stale — run without --check to regenerate" >&2
        exit 1
    fi
fi

mv "$new_index" "$INDEX"
echo "[index-investigations] INDEX.md regenerated ($total investigations: $count_open open, $count_closed closed, $count_implemented implemented)"
exit 0
