package commentaudit

import (
	"strings"
	"testing"
)

const base = `//go:build linux

// Package demo does a thing.
package demo

import "fmt"

// cycle-1234 showed the retry must come first (see incident X).
func run(n int) string {
	// narrative that restates the code
	x := n + 1 // trailing note
	/* block note */
	return fmt.Sprint(x)
}
`

func TestEquivalent(t *testing.T) {
	for _, tc := range []struct {
		name, after string
		want        bool
		reason      string
	}{
		{name: "comments removed and blank lines shifted", want: true, after: `//go:build linux

package demo

import "fmt"


func run(n int) string {
	x := n + 1
	return fmt.Sprint(x)
}
`},
		{name: "comments rewritten", want: true, after: strings.Replace(base, "narrative that restates the code", "why: n is 0-based", 1)},
		{name: "identifier renamed", want: false, reason: "code", after: strings.Replace(base, "x := n + 1 // trailing note", "y := n + 1", 1)},
		{name: "literal changed", want: false, reason: "code", after: strings.Replace(base, "n + 1", "n + 2", 1)},
		{name: "statements reordered", want: false, reason: "code", after: strings.Replace(strings.Replace(base, "\tx := n + 1 // trailing note\n", "", 1), "\treturn fmt.Sprint(x)\n", "\treturn fmt.Sprint(x)\n\tx := n + 1\n", 1)},
		{name: "build directive removed", want: false, reason: "directive", after: strings.Replace(base, "//go:build linux\n", "", 1)},
		{name: "build directive changed", want: false, reason: "directive", after: strings.Replace(base, "//go:build linux", "//go:build darwin", 1)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, reason, err := Equivalent("demo.go", []byte(base), []byte(tc.after))
			if err != nil {
				t.Fatalf("Equivalent: %v", err)
			}
			if got != tc.want {
				t.Fatalf("Equivalent = %v (%s), want %v", got, reason, tc.want)
			}
			if !tc.want && !strings.Contains(reason, tc.reason) {
				t.Fatalf("reason %q must name %q", reason, tc.reason)
			}
		})
	}
}

func TestEquivalent_UnparsableSourceIsAnError(t *testing.T) {
	if _, _, err := Equivalent("demo.go", []byte(base), []byte("package demo\nfunc {")); err == nil {
		t.Fatal("an unparsable after must be an error, not a verdict")
	}
}

func TestDirectives(t *testing.T) {
	src := `// Code generated by stringer; DO NOT EDIT.

//go:build !windows
// +build !windows

package p

import _ "embed"

//go:embed data.txt
var data string

//nolint:gocyclo // long switch
func f() {}

// just a note
//line foo.go:10
	// acs-predicate: config-check
	// minimal: linear scan; index it past 10k items
`
	want := []string{
		"// Code generated by stringer; DO NOT EDIT.",
		"//go:build !windows",
		"// +build !windows",
		"//go:embed data.txt",
		"//nolint:gocyclo // long switch",
		"//line foo.go:10",
		"// acs-predicate: config-check",
		"// minimal: linear scan; index it past 10k items",
	}
	got := Directives([]byte(src))
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("Directives =\n%s\nwant\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

func TestEquivalent_TheCgoPreambleIsCode(t *testing.T) {
	const cgo = "package p\n\n// #include <stdio.h>\n// #define N 1\nimport \"C\"\n\n// a note\nimport \"fmt\"\n\nvar _ = fmt.Sprint\n"
	changed := strings.Replace(cgo, "#define N 1", "#define N 2", 1)
	if ok, reason, err := Equivalent("p.go", []byte(cgo), []byte(changed)); err != nil || ok || !strings.Contains(reason, "code") {
		t.Fatalf("a cgo preamble change is a code change: ok=%v reason=%q err=%v", ok, reason, err)
	}
	noteOnly := strings.Replace(cgo, "// a note\n", "", 1)
	if ok, _, err := Equivalent("p.go", []byte(cgo), []byte(noteOnly)); err != nil || !ok {
		t.Fatalf("a comment above an ordinary import is still only a comment: ok=%v err=%v", ok, err)
	}
}

func TestEquivalent_AGroupedImportHeaderIsNotAPreamble(t *testing.T) {
	const grouped = "package p\n\n// the imports\nimport (\n\t\"C\"\n\t\"fmt\"\n)\n\nvar _ = fmt.Sprint\n"
	if ok, _, err := Equivalent("p.go", []byte(grouped), []byte(strings.Replace(grouped, "// the imports\n", "", 1))); err != nil || !ok {
		t.Fatalf("a header over a grouped import block is a plain comment: ok=%v err=%v", ok, err)
	}
}

func TestEquivalent_TrailingAndAttachedDirectivesAreProtected(t *testing.T) {
	const src = "package p\n\nimport \"errors\"\n\n//go:noinline\nfunc A() {}\n\nfunc B() {}\n\nfunc C() error {\n\t_ = errors.New(\"x\") //nolint:errcheck\n\treturn nil\n}\n"
	for name, after := range map[string]string{
		"trailing nolint removed":                strings.Replace(src, " //nolint:errcheck", "", 1),
		"directive moved to another declaration": strings.Replace(strings.Replace(src, "//go:noinline\nfunc A() {}", "func A() {}", 1), "func B() {}", "//go:noinline\nfunc B() {}", 1),
	} {
		if ok, reason, err := Equivalent("p.go", []byte(src), []byte(after)); err != nil || ok || !strings.Contains(reason, "directive") {
			t.Errorf("%s: ok=%v reason=%q err=%v", name, ok, reason, err)
		}
	}
	raw := "package p\n\nvar s = `\n//go:embed not-a-directive\n`\n"
	if got := Directives([]byte(raw)); len(got) != 0 {
		t.Errorf("text inside a raw string is not a directive: %q", got)
	}
}

func TestDirectives_DeprecatedAndExampleOutputAreProtected(t *testing.T) {
	src := "package p\n\n// Deprecated: use B.\nfunc A() {}\n\nfunc ExampleB() {\n\t// Output: 1\n}\n"
	got := strings.Join(Directives([]byte(src)), "\n")
	for _, want := range []string{"// Deprecated: use B.", "// Output: 1"} {
		if !strings.Contains(got, want) {
			t.Errorf("Directives must protect %q, got:\n%s", want, got)
		}
	}
}

func TestEquivalent_ATrailingDirectiveMovedToTheNextStatementIsAChange(t *testing.T) {
	const trailing = "package p\n\nfunc f() {\n\ty := b() //nolint:errcheck\n\tz()\n\t_ = y\n}\n\nfunc b() error { return nil }\n\nfunc z() {}\n"
	moved := strings.Replace(trailing, "\ty := b() //nolint:errcheck\n\tz()", "\ty := b()\n\t//nolint:errcheck\n\tz()", 1)
	if ok, reason, err := Equivalent("p.go", []byte(trailing), []byte(moved)); err != nil || ok || !strings.Contains(reason, "directive") {
		t.Fatalf("the directive now applies to z(), not y := b(): ok=%v reason=%q err=%v", ok, reason, err)
	}
}

func TestEquivalent_AnOptionalSemicolonDoesNotMoveADirective(t *testing.T) {
	const withSemicolon = "package p\n\nfunc f() {\n\tx := 1;\n\t_ = x\n}\n\n//go:noinline\nfunc g() {}\n"
	without := strings.Replace(withSemicolon, "x := 1;", "x := 1", 1)
	if ok, reason, err := Equivalent("p.go", []byte(withSemicolon), []byte(without)); err != nil || !ok {
		t.Fatalf("the directive still sits on g: ok=%v reason=%q err=%v", ok, reason, err)
	}
}

func TestEquivalent_DirectivePlacementIsPositional(t *testing.T) {
	const twoReturns = "package p\n\nfunc f(a, b func() error) error {\n\tif err := a(); err != nil {\n\t\treturn err //nolint:wrapcheck\n\t}\n\tif err := b(); err != nil {\n\t\treturn err\n\t}\n\treturn nil\n}\n"
	const deprecated = "package p\n\n// F does a thing.\n//\n// Deprecated: use G.\nfunc F() {}\n\nfunc G() {}\n"
	for name, c := range map[string]struct{ before, after string }{
		"moved between two identical lines": {twoReturns, strings.Replace(strings.Replace(twoReturns, "return err //nolint:wrapcheck\n", "return err\n", 1), "\t\treturn err\n\t}\n\treturn nil", "\t\treturn err //nolint:wrapcheck\n\t}\n\treturn nil", 1)},
		"trailing made leading":             {twoReturns, strings.Replace(twoReturns, "\t\treturn err //nolint:wrapcheck\n", "\t\t//nolint:wrapcheck\n\t\treturn err\n", 1)},
		"Deprecated separator removed":      {deprecated, strings.Replace(deprecated, "//\n// Deprecated:", "// Deprecated:", 1)},
		"blank line detaches Deprecated":    {deprecated, strings.Replace(deprecated, "// Deprecated: use G.\nfunc F()", "// Deprecated: use G.\n\nfunc F()", 1)},
	} {
		if ok, reason, err := Equivalent("p.go", []byte(c.before), []byte(c.after)); err != nil || ok || !strings.Contains(reason, "directive") {
			t.Errorf("%s: ok=%v reason=%q err=%v", name, ok, reason, err)
		}
	}
	if ok, _, err := Equivalent("p.go", []byte(deprecated), []byte(strings.Replace(deprecated, "// F does a thing.", "// F does one thing.", 1))); err != nil || !ok {
		t.Errorf("rewording the doc above a Deprecated paragraph is still a comment edit: ok=%v err=%v", ok, err)
	}
}

func TestEquivalent_AnExportedIdentifierKeepsItsDoc(t *testing.T) {
	const documented = "package p\n\n// F starts the run.\n// It used to retry in cycle 42.\nfunc F() {}\n\n// T holds state.\ntype T struct{}\n\n// M resets T.\nfunc (T) M() {}\n\nconst (\n\t// A is the first.\n\tA = 1\n)\n\n// helper is internal.\nfunc helper() {}\n\ntype impl struct{}\n\n// Run implements a port.\nfunc (*impl) Run() {}\n\n// Group of settings.\nvar (\n\tG = 1\n)\n"
	for name, after := range map[string]string{
		"func":         strings.Replace(documented, "// F starts the run.\n// It used to retry in cycle 42.\n", "", 1),
		"type":         strings.Replace(documented, "// T holds state.\n", "", 1),
		"method":       strings.Replace(documented, "// M resets T.\n", "", 1),
		"const":        strings.Replace(documented, "\t// A is the first.\n", "", 1),
		"to a bare //": strings.Replace(documented, "// T holds state.\n", "//\n", 1),
		"var group":    strings.Replace(documented, "// Group of settings.\n", "", 1),
	} {
		if ok, reason, err := Equivalent("p.go", []byte(documented), []byte(after)); err != nil || ok || !strings.Contains(reason, "exported doc") {
			t.Errorf("%s doc deleted: ok=%v reason=%q err=%v", name, ok, reason, err)
		}
	}
	for name, after := range map[string]string{
		"shortened":                              strings.Replace(documented, "// It used to retry in cycle 42.\n", "", 1),
		"unexported doc deleted":                 strings.Replace(documented, "// helper is internal.\n", "", 1),
		"a method doc on an unexported receiver": strings.Replace(documented, "// Run implements a port.\n", "", 1),
	} {
		if ok, reason, err := Equivalent("p.go", []byte(documented), []byte(after)); err != nil || !ok {
			t.Errorf("%s is a comment edit: ok=%v reason=%q err=%v", name, ok, reason, err)
		}
	}
	testFuncDocDeleted := strings.Replace(documented, "// F starts the run.\n// It used to retry in cycle 42.\n", "", 1)
	if ok, _, err := Equivalent("p_test.go", []byte(documented), []byte(testFuncDocDeleted)); err != nil || !ok {
		t.Errorf("test files carry no exported API: ok=%v err=%v", ok, err)
	}
}

func TestDirectives_TheIPCProtocolWaiverIsProtectedWhereverItSits(t *testing.T) {
	src := "package p\n\nconst k = \"EVOLVE_\" + \"STAGE\" // SSOT IPC-protocol-allowed\n\n// v reads the stage key. SSOT IPC-protocol-allowed\nvar v = k\n\n// w is the fan-out token. SSOT §IPC-protocol-allowed\nvar w = k\n"
	if got := Directives([]byte(src)); len(got) != 3 {
		t.Fatalf("the envtaint gate reads either spelling anywhere in a comment, got %q", got)
	}
}

func TestDirectives_ApicoverIgnoreIsProtected(t *testing.T) {
	src := "package p\n\n//apicover:ignore reason=internal seam\nfunc A() {}\n\n// apicover:ignore reason=test hook\nfunc B() {}\n"
	if got := Directives([]byte(src)); len(got) != 2 {
		t.Fatalf("both apicover:ignore forms are machine-read markers, got %q", got)
	}
}
