package commentaudit

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func strippedSource(t *testing.T, name, src string) string {
	t.Helper()
	out, err := StripComments(name, []byte(src))
	if err != nil {
		t.Fatalf("StripComments(%s): %v", name, err)
	}
	return string(out.Source)
}

func strippedKeepingDoc(t *testing.T, name, src string) StrippedFile {
	t.Helper()
	out, err := StripCommentsKeepingPackageDoc(name, []byte(src))
	if err != nil {
		t.Fatalf("StripCommentsKeepingPackageDoc(%s): %v", name, err)
	}
	return out
}

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(got)
}

func TestStripComments_RemovesDocTrailingAndInlineCommentsAndLeavesTheCode(t *testing.T) {
	src := "package p\n\n// F doubles n.\n// It never fails.\nfunc F(n int) int {\n\t// the doubling\n\treturn n * 2 // cheap\n}\n\nvar x = g(1 /* one */, 2)\n\nfunc g(a, b int) int { return a + b }\n"
	want := "package p\n\nfunc F(n int) int {\n\treturn n * 2\n}\n\nvar x = g(1, 2)\n\nfunc g(a, b int) int { return a + b }\n"

	if got := strippedSource(t, "p.go", src); got != want {
		t.Errorf("stripped =\n%s\nwant\n%s", got, want)
	}
}

func TestStripComments_AnInlineCommentBetweenTokensLeavesASpace(t *testing.T) {
	src := "package p\n\nfunc F() int { return/* c */1 }\n"

	if got := strippedSource(t, "p.go", src); got != "package p\n\nfunc F() int { return 1 }\n" {
		t.Errorf("stripped = %q, want the comment replaced by the space the language reads it as", got)
	}
}

func TestStripComments_ReportsTheCommentLinesItRemoved(t *testing.T) {
	src := "package p\n\n// one\n// two\nfunc F() {} // three\n\n/*\nfour\nfive\n*/\nvar V int\n"

	out, err := StripComments("p.go", []byte(src))

	if err != nil || out.Removed != 7 {
		t.Errorf("StripComments = (%d, %v), want 7 removed comment lines", out.Removed, err)
	}
}

func TestStripComments_KeepsWhatAToolReads(t *testing.T) {
	src := "//go:build linux\n\npackage p\n\nimport _ \"embed\"\n\n//go:generate stringer -type=K\n\n// K is a kind.\ntype K int\n\n// Old is old.\n//\n// Deprecated: use New.\nfunc Old() {}\n\n//go:embed x.txt\nvar s string\n\nfunc New() {} //nolint:unused\n\n// acs-predicate: config-check\nvar c = 1\n"

	got := strippedSource(t, "p.go", src)

	for _, keep := range []string{"//go:build linux", "//go:generate stringer -type=K", "// Deprecated: use New.", "//go:embed x.txt", "//nolint:unused", "// acs-predicate: config-check"} {
		if !strings.Contains(got, keep) {
			t.Errorf("stripped dropped %q:\n%s", keep, got)
		}
	}
	for _, gone := range []string{"K is a kind", "Old is old"} {
		if strings.Contains(got, gone) {
			t.Errorf("stripped kept %q:\n%s", gone, got)
		}
	}
}

func TestStripComments_KeepsAnExamplesExpectedOutputWhole(t *testing.T) {
	src := "package p_test\n\nimport \"fmt\"\n\n// ExampleHello shows a greeting.\nfunc ExampleHello() {\n\t// print it\n\tfmt.Println(\"hello\")\n\tfmt.Println(\"world\")\n\t// Output:\n\t// hello\n\t// world\n}\n"

	got := strippedSource(t, "p_example_test.go", src)

	if !strings.Contains(got, "\t// Output:\n\t// hello\n\t// world\n") || strings.Contains(got, "shows a greeting") || strings.Contains(got, "print it") {
		t.Errorf("stripped =\n%s\nwant the Output block whole and every other comment gone", got)
	}
}

func TestStripComments_LeavesAGeneratedFileUntouched(t *testing.T) {
	src := "// Code generated by stringer; DO NOT EDIT.\n\npackage p\n\n// K names.\nconst k = 1\n"

	out, err := StripComments("k_string.go", []byte(src))

	if err != nil || out.Removed != 0 || string(out.Source) != src {
		t.Errorf("StripComments = (%q, %d, %v), want a generated file unchanged: its generator owns it", out.Source, out.Removed, err)
	}
}

func TestStripComments_KeepsTheCgoPreambleOfASingleOrAGroupedImport(t *testing.T) {
	single := "package p\n\n// #include <stdio.h>\nimport \"C\"\n\n// F calls C.\nfunc F() {}\n"
	grouped := "package p\n\nimport (\n\t\"fmt\"\n\n\t// #include <stdio.h>\n\t\"C\"\n)\n\n// F calls C.\nfunc F() { fmt.Println() }\n"

	for name, src := range map[string]string{"single": single, "grouped": grouped} {
		got := strippedSource(t, "p.go", src)
		if !strings.Contains(got, "// #include <stdio.h>") || strings.Contains(got, "F calls C") {
			t.Errorf("%s: stripped =\n%s\nwant the cgo preamble kept: cgo compiles it as C", name, got)
		}
	}
}

func TestStripCommentsKeepingPackageDoc_KeepsADocWithinThreeLinesAndSixWords(t *testing.T) {
	threeLines := "// Package p reads the loop's ledger\n// and reports the gaps\n// it finds.\npackage p\n"

	if got := strippedKeepingDoc(t, "p.go", threeLines); string(got.Source) != threeLines || got.PackageDocToWrite {
		t.Errorf("stripped = %+v, want a three-line doc of six words kept as it is", got)
	}
}

func TestStripCommentsKeepingPackageDoc_ShortensALongDocToItsLeadingSentences(t *testing.T) {
	long := "// Package p ports a script. It reads the ledger and reports each gap.\n// The ledger is\n// append-only and\n// never rewritten.\npackage p\n"

	got := strippedKeepingDoc(t, "p.go", long)

	if want := "// Package p ports a script. It reads the ledger and reports each gap.\npackage p\n"; string(got.Source) != want || got.Removed != 3 {
		t.Errorf("stripped = %q (removed %d), want the sentences that reach six words, on one line, and 3 lines removed", got.Source, got.Removed)
	}
}

func TestStripCommentsKeepingPackageDoc_LeavesADocItCannotShortenForAPersonToWrite(t *testing.T) {
	underTheFloor := "// Package p is a port.\npackage p\n"

	got := strippedKeepingDoc(t, "p.go", underTheFloor)

	if string(got.Source) != underTheFloor || !got.PackageDocToWrite {
		t.Errorf("stripped = %+v, want the doc left as it is and flagged: under six words, no sentence can make it valid", got)
	}
}

func TestStripComments_DropsThePackageDocOfAFileThatDoesNotHoldIt(t *testing.T) {
	if got := strippedSource(t, "p.go", "// Package p reads the loop's ledger for gaps.\npackage p\n"); got != "package p\n" {
		t.Errorf("stripped = %q, want no package doc", got)
	}
}

func TestStripComments_RefusesAChangeThatWouldMoveAMarker(t *testing.T) {
	src := "// Package p reads the ledger and reports each gap. It runs daily\n// at dawn.\n//\n// Deprecated: use package q.\npackage p\n"

	_, err := StripCommentsKeepingPackageDoc("p.go", []byte(src))

	if err == nil || !strings.Contains(err.Error(), "p.go") {
		t.Errorf("StripCommentsKeepingPackageDoc = %v, want a refusal naming p.go: shortening would drop the Deprecated note", err)
	}
}

func TestStripComments_AnEmptiedBlockStillCompilesAndIsFormatted(t *testing.T) {
	src := "package p\n\nfunc F(x bool) {\n\tif x {\n\t\t// nothing to do\n\t}\n\n\t// a note\n\n\t_ = x\n}\n"
	want := "package p\n\nfunc F(x bool) {\n\tif x {\n\t}\n\n\t_ = x\n}\n"

	if got := strippedSource(t, "p.go", src); got != want {
		t.Errorf("stripped =\n%s\nwant\n%s", got, want)
	}
}

func TestStripComments_ACommentInsideAStringIsCode(t *testing.T) {
	src := "package p\n\nconst s = \"// not a comment\"\n\nvar r = `/* nor this */`\n"

	if got := strippedSource(t, "p.go", src); got != src {
		t.Errorf("stripped = %q, want the literals unchanged", got)
	}
}

func TestStripComments_KeepsAWholeNoteParagraphAndDropsWhatFollowsIt(t *testing.T) {
	src := "package p\n\n// F is f.\n//\n// minimal: a flat stub. Every tier\n// shares one window today.\n//\n// Unrelated trailing prose.\nfunc F() {}\n\n// Deprecated: use G, which\n// also covers H.\nfunc Old() {}\n\nfunc G() {}\n"

	got := strippedSource(t, "p.go", src)

	for _, keep := range []string{"// minimal: a flat stub. Every tier\n// shares one window today.\nfunc F()", "// Deprecated: use G, which\n// also covers H.\nfunc Old()"} {
		if !strings.Contains(got, keep) {
			t.Errorf("stripped =\n%s\nwant the whole note paragraph %q", got, keep)
		}
	}
	for _, gone := range []string{"F is f.", "Unrelated trailing prose."} {
		if strings.Contains(got, gone) {
			t.Errorf("stripped kept %q:\n%s", gone, got)
		}
	}
}

func TestStripComments_AWhitespaceOnlyCommentLineEndsANote(t *testing.T) {
	src := "package p\n\n// Deprecated: use G.\n// \n// Unrelated prose.\nfunc F() {}\n\nfunc G() {}\n"

	if got := strippedSource(t, "p.go", src); strings.Contains(got, "Unrelated prose") || !strings.Contains(got, "// Deprecated: use G.") {
		t.Errorf("stripped =\n%s\nwant the note kept and the prose after its blank line removed", got)
	}
}

func TestStripComments_KeepsAGroupThatCarriesTheIPCMarkerWhole(t *testing.T) {
	group := "\t// SSOT IPC-protocol-allowed: parent to child handoff, read by the\n\t// envtaint scan, which covers this whole group and the line after it.\n"
	src := "package p\n\nconst (\n" + group + "\tEnvDepth = \"EVOLVE_\" + \"DEPTH\"\n\t// the other key\n\tEnvOther = \"x\"\n)\n"

	got := strippedSource(t, "p.go", src)

	if !strings.Contains(got, group+"\tEnvDepth") || strings.Contains(got, "the other key") {
		t.Errorf("stripped =\n%s\nwant the marker's group kept whole above its declaration and other comments gone", got)
	}
}

func TestStripComments_IsIdempotent(t *testing.T) {
	src := "package p // the package\n\n// F is f.\n//\n// Deprecated: use G.\nfunc F() {} // trailing\n\nfunc G() {}\n"

	once := strippedSource(t, "p.go", src)
	twice, err := StripComments("p.go", []byte(once))

	if err != nil || twice.Removed != 0 || string(twice.Source) != once {
		t.Errorf("second strip = (%q, %d, %v), want nothing left to remove from %q", twice.Source, twice.Removed, err, once)
	}
	if strings.Contains(once, "the package") || !strings.HasPrefix(once, "package p\n") {
		t.Errorf("stripped = %q, want the comment on the package line gone", once)
	}
}

func TestStripComments_WritesGofmtsLineEndings(t *testing.T) {
	src := "package p\r\n\r\n// F is f.\r\nfunc F() {}\r\n"

	if got := strippedSource(t, "p.go", src); got != "package p\n\nfunc F() {}\n" {
		t.Errorf("stripped = %q, want gofmt's form, which ends lines with LF", got)
	}
}

func TestLeadingSentences_EndsAtASentenceBoundaryNotAnAbbreviationOrAColon(t *testing.T) {
	for text, want := range map[string]string{
		"Package p reads files, e.g. a config. It also writes.":   "Package p reads files, e.g. a config.",
		"Package p is the rule for:\n\n- one\n- two":              "Package p is the rule for.",
		"Package p does one thing":                                "Package p does one thing",
		"Package p talks to services, e.g. ACS and CLI. It logs.": "Package p talks to services, e.g. ACS and CLI.",
	} {
		if got := leadingSentences(text, 1); got != want {
			t.Errorf("leadingSentences(%q, 1) = %q, want %q", text, got, want)
		}
	}
}

func TestStripDirs_KeepsOnePackageDocPerPackageAndReportsWhatItDid(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "p")
	writeFiles(t, dir, map[string]string{
		"doc.go":    "// Package p reads the ledger and reports each gap. The ledger is\n// append-only,\n// never rewritten,\n// and read daily.\npackage p\n",
		"a.go":      "// Package p is also documented here, in a second file.\npackage p\n\n// A is a.\nfunc A() {}\n",
		"a_test.go": "// Package p tests the ledger reader thoroughly.\npackage p\n",
	})

	report, err := StripDirs([]string{root})

	if err != nil || !reflect.DeepEqual(report, StripReport{Files: 3, Removed: 6}) {
		t.Fatalf("StripDirs = (%+v, %v), want StripReport{Files: 3, Removed: 6}", report, err)
	}
	for name, want := range map[string]string{
		"doc.go":    "// Package p reads the ledger and reports each gap.\npackage p\n",
		"a.go":      "package p\n\nfunc A() {}\n",
		"a_test.go": "package p\n",
	} {
		if got := readFile(t, filepath.Join(dir, name)); got != want {
			t.Errorf("%s = %q, want %q", name, got, want)
		}
	}
}

func TestPackageDocHolder_PrefersDocGoThenTheDirsOwnFileThenTheFirstNonTestFile(t *testing.T) {
	doc := "// Package p reads the ledger and reports each gap.\npackage p\n"
	for want, files := range map[string][]string{
		"doc.go": {"a.go", "doc.go", "p.go"},
		"p.go":   {"a.go", "p.go"},
		"b.go":   {"a_test.go", "b.go"},
	} {
		dir := filepath.Join(t.TempDir(), "p")
		contents := map[string]string{}
		for _, name := range files {
			contents[name] = doc
		}
		writeFiles(t, dir, contents)

		if got := packageDocHolder(dir, files); got != want {
			t.Errorf("packageDocHolder(%v) = %q, want %q", files, got, want)
		}
	}
}

func TestStripDirs_SkipsWhatIsNotProjectCode(t *testing.T) {
	root := t.TempDir()
	src := "package x\n\n// kept, not project code\nvar V int\n"
	for _, dir := range []string{"testdata", "vendor/v", ".cache"} {
		writeFiles(t, filepath.Join(root, dir), map[string]string{"x.go": src})
	}

	if _, err := StripDirs([]string{root}); err != nil {
		t.Fatal(err)
	}

	for _, dir := range []string{"testdata", "vendor/v", ".cache"} {
		if got := readFile(t, filepath.Join(root, dir, "x.go")); got != src {
			t.Errorf("%s/x.go was rewritten; Rank's skip set is not project code", dir)
		}
	}
}

func TestStripDirs_RewritesAFileAtomicallyAndKeepsItsMode(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "p.go")
	if err := os.WriteFile(path, []byte("package p\n\n// F is f.\nfunc F() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if report, err := StripDirs([]string{dir}); err != nil || report.Files != 1 {
		t.Fatalf("StripDirs = (%+v, %v)", report, err)
	}

	info, err := os.Stat(path)
	if err != nil || info.Mode().Perm() != 0o600 {
		t.Errorf("mode = %v (%v), want the file's own 0600 kept", info.Mode().Perm(), err)
	}
	if entries, _ := os.ReadDir(dir); len(entries) != 1 {
		t.Errorf("dir holds %d entries, want only p.go: the rewrite must leave no temporary file", len(entries))
	}
}

func TestStripDirs_ReportsAFileItCannotRead(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "p.go")
	if err := os.WriteFile(path, []byte("package p\n\n// F is f.\nfunc F() {}\n"), 0o000); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0o644) })

	report, err := StripDirs([]string{dir})

	if err != nil || len(report.Failed) != 1 || !strings.Contains(report.Failed[0], "p.go") {
		t.Errorf("StripDirs = (%+v, %v), want the unreadable p.go named in Failed", report, err)
	}
}

func TestMain_StripRewritesTheTreeAndSaysHowMuch(t *testing.T) {
	root := t.TempDir()
	writeFiles(t, root, map[string]string{"p.go": "package p\n\n// F is f.\nfunc F() {}\n"})
	var stdout, stderr bytes.Buffer

	code := Main([]string{"strip", root}, &stdout, &stderr, nil)

	if code != 0 || !strings.Contains(stdout.String(), "removed 1 comment line(s) from 1 file(s)") {
		t.Errorf("Main strip = %d, stdout %q, stderr %q", code, stdout.String(), stderr.String())
	}
}

func TestMain_StripExitsOneAndNamesARefusedFile(t *testing.T) {
	root := t.TempDir()
	writeFiles(t, root, map[string]string{"doc.go": "// Package p reads the ledger and reports each gap. It runs daily\n// at dawn.\n//\n// Deprecated: use package q.\npackage p\n"})
	var stdout, stderr bytes.Buffer

	code := Main([]string{"strip", root}, &stdout, &stderr, nil)

	if code != 1 || !strings.Contains(stderr.String(), "doc.go") {
		t.Errorf("Main strip = %d, stderr %q, want exit 1 naming doc.go", code, stderr.String())
	}
}

func TestMain_StripWithoutADirStripsTheWorkingDirectory(t *testing.T) {
	root := t.TempDir()
	writeFiles(t, root, map[string]string{"p.go": "package p\n\n// F is f.\nfunc F() {}\n"})
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var stdout, stderr bytes.Buffer

	code := Main([]string{"strip"}, &stdout, &stderr, nil)

	if code != 0 || readFile(t, filepath.Join(root, "p.go")) != "package p\n\nfunc F() {}\n" {
		t.Errorf("Main strip = %d (stderr %q), want the working directory stripped", code, stderr.String())
	}
}

func TestMain_StripListsThePackageDocsAPersonMustWrite(t *testing.T) {
	root := t.TempDir()
	writeFiles(t, root, map[string]string{"doc.go": "// Package p is a port.\npackage p\n\n// F is f.\nfunc F() {}\n"})
	var stdout, stderr bytes.Buffer

	code := Main([]string{"strip", root}, &stdout, &stderr, nil)

	if code != 0 || !strings.Contains(stdout.String(), "package doc to write: "+filepath.Join(root, "doc.go")) {
		t.Errorf("Main strip = %d, stdout %q, want the under-floor doc listed for a person to write", code, stdout.String())
	}
}

func TestEquivalent_AnchorsOnlyTheParagraphOfANoteToolsRead(t *testing.T) {
	for marker, anchored := range map[string]bool{"// Deprecated: use G.": true, "// minimal: a flat stub.": false} {
		before := "package p\n\n// F is f.\n//\n" + marker + "\nfunc F() {}\n"
		after := "package p\n\n// F is f.\n" + marker + "\nfunc F() {}\n"

		same, why, err := Equivalent("p.go", []byte(before), []byte(after))

		if err != nil || same == anchored {
			t.Errorf("%s: Equivalent = (%v, %q, %v), want equivalent=%v: only a note staticcheck and gopls read is anchored to its paragraph", marker, same, why, err, !anchored)
		}
	}
}

func TestStripCommentsKeepingPackageDoc_KeepsATwoLineDocAtExactlyTheWordFloor(t *testing.T) {
	src := "// Package p reads\n// the ledger daily.\npackage p\n"
	if words := len(strings.Fields("Package p reads the ledger daily.")); words != MinPackageDocWords {
		t.Fatalf("fixture has %d words, want exactly MinPackageDocWords (%d)", words, MinPackageDocWords)
	}

	if got := strippedKeepingDoc(t, "p.go", src); string(got.Source) != src || got.PackageDocToWrite {
		t.Errorf("stripped = %+v, want a doc at the word floor kept as it is", got)
	}
}

func TestStripCommentsKeepingPackageDoc_LeavesALeadingSentenceTooLongForThreeLinesForAPerson(t *testing.T) {
	line := strings.Repeat(" word", 15)
	src := "// Package p" + line + "\n//" + line + "\n//" + line + "\n//" + line + ".\npackage p\n"

	if got := strippedKeepingDoc(t, "p.go", src); string(got.Source) != src || !got.PackageDocToWrite {
		t.Errorf("stripped = %q (to write: %v), want a 60-word first sentence left as written and listed", got.Source, got.PackageDocToWrite)
	}
}

func TestStripCommentsKeepingPackageDoc_WrapsTheShortenedDocWithinTheColumnLimit(t *testing.T) {
	src := "// Package p" + strings.Repeat(" word", 20) + ". More here.\n// a\n// b\n// c\npackage p\n"

	doc := strings.TrimSuffix(string(strippedKeepingDoc(t, "p.go", src).Source), "\npackage p\n")
	lines := strings.Split(doc, "\n")

	if len(lines) != 2 {
		t.Fatalf("doc = %q, want the 22-word sentence wrapped onto 2 lines", doc)
	}
	for _, line := range lines {
		if len(line) > packageDocLineColumns {
			t.Errorf("line %q is %d columns, over %d", line, len(line), packageDocLineColumns)
		}
	}
}

func TestStripComments_AMultiLineInlineCommentLeavesTheNewlineTheLanguageReads(t *testing.T) {
	src := "package p\n\nfunc F() int {\n\tx := 1 /* a\n*/ return x\n}\n"

	if got := strippedSource(t, "p.go", src); got != "package p\n\nfunc F() int {\n\tx := 1\n\treturn x\n}\n" {
		t.Errorf("stripped = %q, want two statements: a comment holding a newline reads as one", got)
	}
}
