package skillcheck

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeSkillFixture(t *testing.T, root, name, desc, argHint string) {
	t.Helper()
	dir := filepath.Join(root, "skills", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", dir, err)
	}
	fm := "---\nname: " + name + "\ndescription: " + desc + "\n"
	if argHint != "" {
		fm += "argument-hint: \"" + argHint + "\"\n"
	}
	fm += "---\n\n# " + name + "\n\nbody\n"
	if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(fm), 0o644); err != nil {
		t.Fatalf("write SKILL.md: %v", err)
	}
}

func TestCommandFileName(t *testing.T) {
	for _, tc := range []struct {
		skill, want string
	}{
		{"loop", "loop.md"},
		{"tdd", "tdd.md"},
		{"security-review-scored", "security-review-scored.md"},
	} {
		got := CommandFileName(tc.skill)
		if got != tc.want {
			t.Errorf("CommandFileName(%q) = %q, want %q", tc.skill, got, tc.want)
		}
		if strings.HasPrefix(got, "evo-") {
			t.Errorf("CommandFileName(%q) keeps the legacy evo- prefix → /evo:evo-%s double-namespace", tc.skill, tc.skill)
		}
	}
}

func TestCommandDiffs_ProjectsStubPerSkill(t *testing.T) {
	root := t.TempDir()
	writeSkillFixture(t, root, "foo", "Do foo work", "[target]")

	diffs, err := commandDiffs(root)
	if err != nil {
		t.Fatalf("commandDiffs: %v", err)
	}

	var got *commandDiff
	for i := range diffs {
		if diffs[i].rel == filepath.Join("commands", "foo.md") {
			got = &diffs[i]
		}
	}
	if got == nil {
		t.Fatalf("no diff for commands/foo.md; got %+v", diffs)
	}
	if !got.drifted {
		t.Errorf("want drifted=true for a missing command file")
	}
	if got.orphan {
		t.Errorf("foo backs a real skill; want orphan=false")
	}
	for _, want := range []string{
		`description: "Do foo work"`,
		`argument-hint: "[target]"`,
		"evo:foo",
		"$ARGUMENTS",
		"GENERATED by",
	} {
		if !strings.Contains(got.next, want) {
			t.Errorf("command content missing %q\n---\n%s", want, got.next)
		}
	}
}
