// commands.go is the second half of ADR-0040's projection: it mirrors every
// skill under skills/ into a thin commands/<name>.md slash-command stub so each
// skill surfaces in the Claude Code `/` menu as /evo:<name>. SKILL.md stays the
// single source — the command carries only the skill's description/argument-hint
// (for the menu) and a body that delegates back to the skill. Generated stubs
// carry a marker so the projection can detect drift and reap orphans without
// ever touching a hand-authored command.
package skillcheck

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mickeyyaya/evolve-loop/go/internal/prompts"
)

// commandGenMarker tags every generated command stub. It is the reap guard in
// the orphan path: a commands/*.md whose backing skill is gone is deleted only
// if it carries this marker, so a hand-authored command is never reaped. (In the
// skill-backed path the evo-<skill> name is itself reserved by CommandFileName,
// so a hand-authored command must not claim it — that namespace is the guard
// there, since a stale evo-<skill>.md is always overwritten to track its skill.)
const commandGenMarker = "<!-- GENERATED by `evolve skills generate` from skills/"

// CommandFileName maps a skill name to its slash-command stub filename. The
// evo- prefix namespaces the command (/evo-loop) so it groups under /evo in the
// Claude Code menu and never collides with the built-in /loop, /tdd, /refactor.
// The single source for the filename convention — shared by the Claude Code
// projection and the agy cross-CLI projection.
func CommandFileName(skillName string) string {
	return "evo-" + skillName + ".md"
}

// commandDiff is one skill→command mirror comparison.
type commandDiff struct {
	rel     string // "commands/<name>.md" — display + drift identity
	path    string // absolute on-disk path
	next    string // desired content; "" when the file is an orphan to remove
	drifted bool   // on-disk content != desired
	orphan  bool   // a generated command whose backing skill no longer exists
}

// commandDiffs renders the desired commands/<name>.md for every skill under
// skills/ and diffs each against disk, then flags orphaned generated commands
// (a marker-bearing command with no backing skill). Pure: no writes, no prints.
func commandDiffs(projectRoot string) ([]commandDiff, error) {
	skillsDir := filepath.Join(projectRoot, "skills")
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return nil, fmt.Errorf("read skills dir: %w", err)
	}

	var diffs []commandDiff
	backed := map[string]bool{}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		raw, readErr := os.ReadFile(filepath.Join(skillsDir, e.Name(), "SKILL.md"))
		if readErr != nil {
			continue // a dir without SKILL.md is not a skill
		}
		fm, _, parseErr := prompts.ParseFrontmatter(string(raw))
		if parseErr != nil {
			continue // nameMismatches already reports unparseable frontmatter as drift
		}
		name, _ := fm["name"].(string)
		if name == "" {
			name = e.Name()
		}
		desc, _ := fm["description"].(string)
		argHint, _ := fm["argument-hint"].(string)

		next := RenderCommandStub(name, desc, argHint)
		fileName := CommandFileName(name)
		base := strings.TrimSuffix(fileName, ".md") // "evo-<name>" — matches the orphan loop key
		path := filepath.Join(projectRoot, "commands", fileName)
		cur, _ := os.ReadFile(path) // missing → "" → drifted
		diffs = append(diffs, commandDiff{
			rel:     filepath.Join("commands", fileName),
			path:    path,
			next:    next,
			drifted: string(cur) != next,
		})
		backed[base] = true
	}

	// Orphans: generated command stubs whose backing skill no longer exists.
	cmdDir := filepath.Join(projectRoot, "commands")
	if cmds, dirErr := os.ReadDir(cmdDir); dirErr == nil {
		for _, c := range cmds {
			if c.IsDir() || !strings.HasSuffix(c.Name(), ".md") {
				continue
			}
			base := strings.TrimSuffix(c.Name(), ".md")
			if backed[base] {
				continue
			}
			path := filepath.Join(cmdDir, c.Name())
			raw, readErr := os.ReadFile(path)
			if readErr != nil || !strings.Contains(string(raw), commandGenMarker) {
				continue // unreadable or hand-authored — never reap
			}
			diffs = append(diffs, commandDiff{
				rel:     filepath.Join("commands", c.Name()),
				path:    path,
				next:    "",
				drifted: true,
				orphan:  true,
			})
		}
	}

	sort.Slice(diffs, func(i, j int) bool { return diffs[i].rel < diffs[j].rel })
	return diffs, nil
}

// RenderCommandStub produces a thin slash-command stub for a skill. It
// duplicates no prose: only the menu-facing description/argument-hint (projected
// from the skill's frontmatter) and a body that hands control straight to the
// skill. Exported so the cross-CLI publisher (agy, a Claude-Code-shaped plugin
// host) projects the identical stub — one source for /evo:<name> everywhere.
func RenderCommandStub(name, desc, argHint string) string {
	hint := ""
	if argHint != "" {
		hint = "argument-hint: " + yamlQuote(argHint) + "\n"
	}
	return fmt.Sprintf(
		"---\ndescription: %s\n%s---\n\n"+
			"%s%s/SKILL.md — DO NOT EDIT. -->\n"+
			"<!-- Edit the skill, then run `evolve skills generate`. -->\n\n"+
			"Run the **%s** skill from the `evo` plugin (Skill tool id `evo:%s`); follow its SKILL.md instructions exactly.\n\n"+
			"Arguments: $ARGUMENTS\n",
		yamlQuote(desc), hint, commandGenMarker, name, name, name,
	)
}

// yamlQuote emits a YAML double-quoted scalar from arbitrary frontmatter text.
// It escapes the metacharacters of the double-quoted style — backslash and the
// quote itself, plus the whitespace controls (newline, CR, tab) that would
// otherwise round-trip lossily (YAML flow-folds a literal newline to a space, so
// an unescaped multi-line value would never re-match its source and would drift
// forever). Skill descriptions carry colons, slashes, and backticks, which are
// already safe inside double quotes; the escaped controls cover the rest.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
