package skillcheck

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeSkillFixture creates skills/<name>/SKILL.md with the given frontmatter so
// the command projection has a single source to mirror.
func writeSkillFixture(t *testing.T, root, name, desc, argHint string) {
	t.Helper()
	dir := filepath.Join(root, "skills", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", dir, err)
	}
	fm := "---\nname: " + name + "\ndescription: " + desc + "\n"
	if argHint != "" {
		fm += "argument-hint: \"" + argHint + "\"\n"
	}
	fm += "---\n\n# " + name + "\n\nbody\n"
	if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(fm), 0o644); err != nil {
		t.Fatalf("write SKILL.md: %v", err)
	}
}

// TestCommandFileName pins the slash-command filename contract: the evo- prefix
// is what namespaces the command under /evo and keeps it from colliding with the
// built-in /loop, /tdd, /refactor. Both projection surfaces (Claude Code and the
// agy cross-CLI publisher) derive their filenames here, so the convention must
// not drift.
func TestCommandFileName(t *testing.T) {
	for _, tc := range []struct {
		skill, want string
	}{
		{"loop", "evo-loop.md"},
		{"tdd", "evo-tdd.md"},
		{"security-review-scored", "evo-security-review-scored.md"},
	} {
		if got := CommandFileName(tc.skill); got != tc.want {
			t.Errorf("CommandFileName(%q) = %q, want %q", tc.skill, got, tc.want)
		}
	}
}

// TestCommandDiffs_ProjectsStubPerSkill is the RED proof: every skill must
// project a commands/<name>.md stub carrying the skill's description and
// argument-hint (for the `/` menu), a delegation to evo:<name>, the $ARGUMENTS
// passthrough, and the GENERATED marker — and report drift when absent on disk.
func TestCommandDiffs_ProjectsStubPerSkill(t *testing.T) {
	root := t.TempDir()
	writeSkillFixture(t, root, "foo", "Do foo work", "[target]")

	diffs, err := commandDiffs(root)
	if err != nil {
		t.Fatalf("commandDiffs: %v", err)
	}

	var got *commandDiff
	for i := range diffs {
		if diffs[i].rel == filepath.Join("commands", "evo-foo.md") {
			got = &diffs[i]
		}
	}
	if got == nil {
		t.Fatalf("no diff for commands/evo-foo.md; got %+v", diffs)
	}
	if !got.drifted {
		t.Errorf("want drifted=true for a missing command file")
	}
	if got.orphan {
		t.Errorf("foo backs a real skill; want orphan=false")
	}
	for _, want := range []string{
		`description: "Do foo work"`,
		`argument-hint: "[target]"`,
		"evo:foo",
		"$ARGUMENTS",
		"GENERATED by",
	} {
		if !strings.Contains(got.next, want) {
			t.Errorf("command content missing %q\n---\n%s", want, got.next)
		}
	}
}
