package skillcheck

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mickeyyaya/evolve-loop/go/internal/prompts"
)

const commandGenMarker = "<!-- GENERATED by `evolve skills generate` from skills/"

func CommandFileName(skillName string) string {
	return skillName + ".md"
}

type commandDiff struct {
	rel     string
	path    string
	next    string
	drifted bool
	orphan  bool
}

func commandDiffs(projectRoot string) ([]commandDiff, error) {
	skillsDir := filepath.Join(projectRoot, "skills")
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return nil, fmt.Errorf("read skills dir: %w", err)
	}

	var diffs []commandDiff
	backed := map[string]bool{}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		raw, readErr := os.ReadFile(filepath.Join(skillsDir, e.Name(), "SKILL.md"))
		if readErr != nil {
			continue
		}
		fm, _, parseErr := prompts.ParseFrontmatter(string(raw))
		if parseErr != nil {
			continue
		}
		name, _ := fm["name"].(string)
		if name == "" {
			name = e.Name()
		}
		desc, _ := fm["description"].(string)
		argHint, _ := fm["argument-hint"].(string)

		next := RenderCommandStub(name, desc, argHint)
		fileName := CommandFileName(name)
		base := strings.TrimSuffix(fileName, ".md")
		path := filepath.Join(projectRoot, "commands", fileName)
		cur, _ := os.ReadFile(path)
		diffs = append(diffs, commandDiff{
			rel:     filepath.Join("commands", fileName),
			path:    path,
			next:    next,
			drifted: string(cur) != next,
		})
		backed[base] = true
	}

	diffs = append(diffs, orphanCommandDiffs(projectRoot, backed)...)

	sort.Slice(diffs, func(i, j int) bool { return diffs[i].rel < diffs[j].rel })
	return diffs, nil
}

func orphanCommandDiffs(projectRoot string, backed map[string]bool) []commandDiff {
	cmdDir := filepath.Join(projectRoot, "commands")
	cmds, dirErr := os.ReadDir(cmdDir)
	if dirErr != nil {
		return nil
	}
	var orphans []commandDiff
	for _, c := range cmds {
		if c.IsDir() || !strings.HasSuffix(c.Name(), ".md") {
			continue
		}
		base := strings.TrimSuffix(c.Name(), ".md")
		if backed[base] {
			continue
		}
		path := filepath.Join(cmdDir, c.Name())
		raw, readErr := os.ReadFile(path)
		isGeneratedStub := readErr == nil && strings.Contains(string(raw), commandGenMarker)
		if !isGeneratedStub {
			continue
		}
		orphans = append(orphans, commandDiff{
			rel:     filepath.Join("commands", c.Name()),
			path:    path,
			next:    "",
			drifted: true,
			orphan:  true,
		})
	}
	return orphans
}

func RenderCommandStub(name, desc, argHint string) string {
	hint := ""
	if argHint != "" {
		hint = "argument-hint: " + yamlQuote(argHint) + "\n"
	}
	return fmt.Sprintf(
		"---\ndescription: %s\n%s---\n\n"+
			"%s%s/SKILL.md — DO NOT EDIT. -->\n"+
			"<!-- Edit the skill, then run `evolve skills generate`. -->\n\n"+
			"Read `${CLAUDE_PLUGIN_ROOT}/skills/%s/SKILL.md` and follow its instructions exactly.\n\n"+
			"Arguments: $ARGUMENTS\n",
		yamlQuote(desc), hint, commandGenMarker, name, name,
	)
}

// Escaping the controls keeps a multi-line description round-tripping; YAML folds a raw newline, so the stub would drift forever.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}
