package changeloggen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestClassify_AllTypeFamilies(t *testing.T) {
	tests := []struct {
		subject string
		bucket  string
		want    string
	}{
		{"feat: add new thing", "Added", "add new thing"},
		{"feature: another", "Added", "another"},
		{"fix: bug", "Fixed", "bug"},
		{"bugfix: another bug", "Fixed", "another bug"},
		{"refactor: cleanup", "Changed", "cleanup"},
		{"perf: optimize", "Changed", "optimize"},
		{"performance: hot path", "Changed", "hot path"},
		{"stability: race fix", "Changed", "race fix"},
		{"techdebt: cleanup", "Changed", "cleanup"},
		{"docs: explain it", "Docs", "explain it"},
		{"documentation: longer", "Docs", "longer"},
		{"doc: short", "Docs", "short"},
		{"feat(v11.6.5): scoped", "Added", "scoped"},
		{"fix(scope): scoped fix", "Fixed", "scoped fix"},
		{"FEAT: uppercase", "Added", "uppercase"},
		{"Feat: titlecase", "Added", "titlecase"},
	}
	for _, tc := range tests {
		t.Run(tc.subject, func(t *testing.T) {
			var b Buckets
			Classify(tc.subject, &b)
			var actual []string
			switch tc.bucket {
			case "Added":
				actual = b.Added
			case "Fixed":
				actual = b.Fixed
			case "Changed":
				actual = b.Changed
			case "Docs":
				actual = b.Docs
			case "Other":
				actual = b.Other
			}
			if len(actual) != 1 || actual[0] != tc.want {
				t.Errorf("got %v, want [%q] in %s", actual, tc.want, tc.bucket)
			}
		})
	}
}

func TestClassify_SkippedTypes(t *testing.T) {
	for _, sub := range []string{
		"chore: bump deps", "ci: tweak workflow", "test: more cases",
		"build: speed up", "style: format", "revert: revert that",
		"meta: housekeeping", "release: v1",
	} {
		var b Buckets
		Classify(sub, &b)
		if !b.Empty() {
			t.Errorf("subject %q should be skipped, got %+v", sub, b)
		}
	}
}

func TestClassify_UnknownTypeBucketsToOtherWithTag(t *testing.T) {
	var b Buckets
	Classify("hotfix: emergency rollback", &b)
	if len(b.Other) != 1 || b.Other[0] != "(hotfix) emergency rollback" {
		t.Errorf("got %v, want [(hotfix) emergency rollback]", b.Other)
	}
}

func TestClassify_NoTypePrefixGoesToOther(t *testing.T) {
	var b Buckets
	Classify("just a freeform subject line", &b)
	if len(b.Other) != 1 || b.Other[0] != "just a freeform subject line" {
		t.Errorf("got %v", b.Other)
	}
}

func TestClassify_MultiWordType(t *testing.T) {
	// "feat-extra" doesn't match the regex (hyphen breaks [A-Za-z]+).
	var b Buckets
	Classify("feat-extra: thing", &b)
	if len(b.Other) != 1 || b.Other[0] != "feat-extra: thing" {
		t.Errorf("got %v", b.Other)
	}
}

func TestClassifyAll(t *testing.T) {
	commits := []Commit{
		{SHA: "a", Subject: "feat: x"},
		{SHA: "b", Subject: "fix: y"},
		{SHA: "c", Subject: "chore: skip me"},
		{SHA: "d", Subject: "no type prefix"},
	}
	b := ClassifyAll(commits)
	if len(b.Added) != 1 || b.Added[0] != "x" {
		t.Errorf("Added=%v", b.Added)
	}
	if len(b.Fixed) != 1 || b.Fixed[0] != "y" {
		t.Errorf("Fixed=%v", b.Fixed)
	}
	if len(b.Other) != 1 || b.Other[0] != "no type prefix" {
		t.Errorf("Other=%v", b.Other)
	}
}

func TestRenderEntry_AllSections(t *testing.T) {
	b := Buckets{
		Added:   []string{"a1", "a2"},
		Fixed:   []string{"f1"},
		Changed: []string{"c1"},
		Docs:    []string{"d1"},
		Other:   []string{"o1"},
	}
	now := time.Date(2026, 5, 24, 12, 0, 0, 0, time.UTC)
	got := RenderEntry("11.6.7", "v11.6.6", "HEAD", now, b)

	for _, want := range []string{
		"## [11.6.7] - 2026-05-24\n",
		"_Generated by `legacy/scripts/release/changelog-gen.sh` from commits v11.6.6..HEAD._",
		"### Added\n\n- a1\n- a2\n",
		"### Fixed\n\n- f1\n",
		"### Changed\n\n- c1\n",
		"### Documentation\n\n- d1\n",
		"### Other\n\n- o1\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if !strings.HasSuffix(got, "\n---\n\n") {
		t.Errorf("missing trailer:\n%s", got)
	}
}

func TestRenderEntry_OnlyAddedSection(t *testing.T) {
	b := Buckets{Added: []string{"x"}}
	now := time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC)
	got := RenderEntry("1.0.0", "from", "to", now, b)
	if !strings.Contains(got, "### Added") {
		t.Errorf("missing Added section")
	}
	if strings.Contains(got, "### Fixed") || strings.Contains(got, "### Documentation") {
		t.Errorf("unexpected empty sections present:\n%s", got)
	}
}

func TestRenderEntry_EmptyBucketsPlaceholder(t *testing.T) {
	now := time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC)
	got := RenderEntry("1.0.0", "v0", "HEAD", now, Buckets{})
	if !strings.Contains(got, "### Other\n\n- (no commits found in range; placeholder entry)") {
		t.Errorf("missing placeholder: %s", got)
	}
}

func TestHasEntry(t *testing.T) {
	body := "# Changelog\n\n## [11.6.6] - 2026-05-24\n\n- thing\n\n## [11.6.5]\n"
	if !HasEntry(body, "11.6.6") {
		t.Errorf("should find 11.6.6")
	}
	if !HasEntry(body, "11.6.5") {
		t.Errorf("should find 11.6.5")
	}
	if HasEntry(body, "11.6.7") {
		t.Errorf("should not find 11.6.7")
	}
}

func TestHasEntry_MidLineNotMatched(t *testing.T) {
	// `## [11.6.6]` must be at line start.
	body := "comment ## [11.6.6] referenced"
	if HasEntry(body, "11.6.6") {
		t.Errorf("mid-line should not match")
	}
}

func TestPrependEntry_BeforeFirstVersion(t *testing.T) {
	body := "# Changelog\n\nIntro paragraph.\n\n## [1.0.0]\n\n- existing\n"
	entry := "## [1.1.0]\n\n- new\n\n---\n\n"
	got := PrependEntry(body, entry)
	if !strings.Contains(got, "Intro paragraph.\n\n## [1.1.0]\n") {
		t.Errorf("entry not inserted after header: %s", got)
	}
	if !strings.Contains(got, "## [1.1.0]\n\n- new\n\n---\n\n## [1.0.0]") {
		t.Errorf("entry not before old version: %s", got)
	}
}

func TestPrependEntry_NoExistingVersion(t *testing.T) {
	body := "# Changelog\n\nIntro only.\n"
	entry := "## [1.0.0]\n\n- first\n\n---\n\n"
	got := PrependEntry(body, entry)
	if !strings.HasSuffix(got, entry) {
		t.Errorf("entry not appended at end: %s", got)
	}
}

func TestFirstVersionBlock_RequiresLineStart(t *testing.T) {
	body := "comment ## [1.0.0]\n\nreal ## [1.0.0]\n## [2.0.0]\n"
	idx := firstVersionBlock(body)
	if idx < 0 {
		t.Errorf("should find a version block")
	}
	if body[idx:idx+10] != "## [2.0.0]" {
		t.Errorf("found wrong block: %q", body[idx:idx+10])
	}
}

func TestFirstVersionBlock_None(t *testing.T) {
	if firstVersionBlock("just a body") != -1 {
		t.Errorf("expected -1")
	}
}

func TestWriteEntry_FreshFile(t *testing.T) {
	tmp := t.TempDir()
	cl := filepath.Join(tmp, "CHANGELOG.md")
	entry := "## [1.0.0]\n\n- x\n\n---\n\n"
	wrote, skipped, err := WriteEntry(cl, "1.0.0", entry)
	if err != nil {
		t.Fatalf("%v", err)
	}
	if !wrote || skipped {
		t.Errorf("wrote=%v skipped=%v, want true/false", wrote, skipped)
	}
	body, _ := os.ReadFile(cl)
	if !strings.Contains(string(body), DefaultFreshContent) {
		t.Errorf("missing default header: %s", body)
	}
	if !strings.Contains(string(body), entry) {
		t.Errorf("missing entry: %s", body)
	}
}

func TestWriteEntry_Idempotent(t *testing.T) {
	tmp := t.TempDir()
	cl := filepath.Join(tmp, "CHANGELOG.md")
	seed := "# Changelog\n\n## [1.0.0]\n\nfirst run\n\n---\n\n"
	_ = os.WriteFile(cl, []byte(seed), 0o644)

	entry := "## [1.0.0]\n\n- different but version matches\n\n---\n\n"
	wrote, skipped, err := WriteEntry(cl, "1.0.0", entry)
	if err != nil {
		t.Fatalf("%v", err)
	}
	if wrote || !skipped {
		t.Errorf("wrote=%v skipped=%v, want false/true", wrote, skipped)
	}
	// Original content unchanged.
	body, _ := os.ReadFile(cl)
	if string(body) != seed {
		t.Errorf("body mutated: %s", body)
	}
}

func TestWriteEntry_PrependPreservesHeader(t *testing.T) {
	tmp := t.TempDir()
	cl := filepath.Join(tmp, "CHANGELOG.md")
	seed := "# Changelog\n\nIntro line.\n\n## [1.0.0]\n\nfirst run\n\n---\n\n"
	_ = os.WriteFile(cl, []byte(seed), 0o644)

	entry := "## [1.1.0]\n\n- new\n\n---\n\n"
	wrote, skipped, err := WriteEntry(cl, "1.1.0", entry)
	if err != nil {
		t.Fatalf("%v", err)
	}
	if !wrote || skipped {
		t.Errorf("expected fresh write")
	}
	body, _ := os.ReadFile(cl)
	if !strings.Contains(string(body), "Intro line.\n\n## [1.1.0]") {
		t.Errorf("header not preserved: %s", body)
	}
}

func TestIsSemver(t *testing.T) {
	for _, ok := range []string{"1.0.0", "11.6.6", "0.0.1"} {
		if !IsSemver(ok) {
			t.Errorf("expected %q valid", ok)
		}
	}
	for _, bad := range []string{"v1.0.0", "1.0", "1.0.0-beta", "abc"} {
		if IsSemver(bad) {
			t.Errorf("expected %q invalid", bad)
		}
	}
}

func TestResolveChangelogPath(t *testing.T) {
	if got := ResolveChangelogPath("/foo"); got != "/foo/CHANGELOG.md" {
		t.Errorf("got %q", got)
	}
}

func TestAppendBucket_EmptyNoOp(t *testing.T) {
	var sb strings.Builder
	appendBucket(&sb, "X", nil)
	if sb.Len() != 0 {
		t.Errorf("expected empty, got %q", sb.String())
	}
}

func TestBucketsEmpty(t *testing.T) {
	if !(Buckets{}).Empty() {
		t.Errorf("zero buckets should be empty")
	}
	if (Buckets{Added: []string{"x"}}).Empty() {
		t.Errorf("non-zero should not be empty")
	}
}
