// Package changeloggen ports legacy/scripts/release/changelog-gen.sh.
//
// Pure-function conventional-commits parser: takes a list of commit subjects
// (typically from `git log <from>..<to>`) and renders a Keep-a-Changelog
// style `## [<version>] - <date>` block grouped into Added/Fixed/Changed/
// Documentation/Other buckets.
//
// Idempotency: if a CHANGELOG.md already has a `## [<version>]` heading for
// the target version, the prepend is a no-op (manual curation preserved).
package changeloggen

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Commit is one commit subject line passed to Classify.
type Commit struct {
	SHA     string
	Subject string // first line of commit message
}

// Buckets is the grouped output of Classify.
type Buckets struct {
	Added   []string
	Fixed   []string
	Changed []string
	Docs    []string
	Other   []string
}

// Empty reports whether all buckets are empty.
func (b Buckets) Empty() bool {
	return len(b.Added)+len(b.Fixed)+len(b.Changed)+len(b.Docs)+len(b.Other) == 0
}

// typeScopeRE matches "<type>(<scope>): <rest>". Bash uses two separate
// sed patterns; we merge into one with named capture for readability.
var typeScopeRE = regexp.MustCompile(`^([A-Za-z]+)(?:\(([^)]+)\))?:[ \t]*(.*)$`)

// Classify buckets a single commit subject into the right Keep-a-Changelog
// section. Mirrors the bash classify() function at changelog-gen.sh:116.
//
// Recognized types (case-insensitive):
//   - feat | feature                            → Added
//   - fix | bugfix                              → Fixed
//   - refactor | perf | performance | stability | techdebt → Changed
//   - docs | documentation | doc                → Docs
//   - chore | ci | test | build | style | revert | meta | release → skipped
//   - any other typed prefix                    → Other (with "(<type>)" tag)
//   - no recognized prefix                      → Other (raw subject)
func Classify(subject string, into *Buckets) {
	m := typeScopeRE.FindStringSubmatch(subject)
	if m == nil {
		into.Other = append(into.Other, subject)
		return
	}
	typeName := strings.ToLower(m[1])
	rest := m[3]
	switch typeName {
	case "feat", "feature":
		into.Added = append(into.Added, rest)
	case "fix", "bugfix":
		into.Fixed = append(into.Fixed, rest)
	case "refactor", "perf", "performance", "stability", "techdebt":
		into.Changed = append(into.Changed, rest)
	case "docs", "documentation", "doc":
		into.Docs = append(into.Docs, rest)
	case "chore", "ci", "test", "build", "style", "revert", "meta", "release":
		// skipped by convention
	default:
		into.Other = append(into.Other, fmt.Sprintf("(%s) %s", typeName, rest))
	}
}

// ClassifyAll runs Classify over every commit, returning grouped buckets.
func ClassifyAll(commits []Commit) Buckets {
	var b Buckets
	for _, c := range commits {
		Classify(c.Subject, &b)
	}
	return b
}

// RenderEntry produces the `## [<version>] - <date>\n\n...\n---\n\n` block.
// fromRef + toRef appear in the generator-byline; date is taken from now.
// Mirrors bash render section at changelog-gen.sh:152-174.
func RenderEntry(version, fromRef, toRef string, now time.Time, b Buckets) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## [%s] - %s\n\n", version, now.Format("2006-01-02"))
	fmt.Fprintf(&sb, "_Generated by `legacy/scripts/release/changelog-gen.sh` from commits %s..%s._\n\n", fromRef, toRef)
	appendBucket(&sb, "Added", b.Added)
	appendBucket(&sb, "Fixed", b.Fixed)
	appendBucket(&sb, "Changed", b.Changed)
	appendBucket(&sb, "Documentation", b.Docs)
	appendBucket(&sb, "Other", b.Other)
	if b.Empty() {
		sb.WriteString("### Other\n\n- (no commits found in range; placeholder entry)\n\n")
	}
	sb.WriteString("\n---\n\n")
	return sb.String()
}

func appendBucket(sb *strings.Builder, heading string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(sb, "### %s\n\n", heading)
	for _, item := range items {
		fmt.Fprintf(sb, "- %s\n", item)
	}
	sb.WriteString("\n")
}

// HasEntry reports whether the CHANGELOG body already contains a
// `## [<version>]` heading. Used for the idempotency skip.
func HasEntry(body, version string) bool {
	pattern := regexp.MustCompile(fmt.Sprintf(`(?m)^## \[%s\]`, regexp.QuoteMeta(version)))
	return pattern.MatchString(body)
}

// PrependEntry inserts entry into body AFTER the file header (everything up
// to the first `## [` line) and BEFORE the existing first version block.
// When there is no version block at all, entry is appended. Mirrors bash
// lines 200-215.
func PrependEntry(body, entry string) string {
	loc := firstVersionBlock(body)
	if loc < 0 {
		// No version blocks: append.
		return body + entry
	}
	return body[:loc] + entry + body[loc:]
}

// firstVersionBlock returns the byte offset of the first `## [` line in
// body, or -1 if none. Matches bash's `grep -nE '^## \[' | head -1`.
func firstVersionBlock(body string) int {
	pos := 0
	for {
		idx := strings.Index(body[pos:], "## [")
		if idx < 0 {
			return -1
		}
		abs := pos + idx
		// Must be at line start.
		if abs == 0 || body[abs-1] == '\n' {
			return abs
		}
		pos = abs + 1
	}
}

// DefaultFreshContent is what we write when CHANGELOG.md doesn't exist.
const DefaultFreshContent = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n"

// WriteEntry writes (or no-ops idempotent) the entry to the CHANGELOG at
// changelogPath. Returns (didWrite, skippedIdempotent, err). Mirrors bash
// main flow at changelog-gen.sh:177-216.
func WriteEntry(changelogPath, version, entry string) (bool, bool, error) {
	body, err := os.ReadFile(changelogPath)
	if err != nil {
		if os.IsNotExist(err) {
			fresh := DefaultFreshContent + entry
			if err := os.WriteFile(changelogPath, []byte(fresh), 0o644); err != nil {
				return false, false, fmt.Errorf("changeloggen: create fresh: %w", err)
			}
			return true, false, nil
		}
		return false, false, fmt.Errorf("changeloggen: read changelog: %w", err)
	}
	if HasEntry(string(body), version) {
		return false, true, nil
	}
	updated := PrependEntry(string(body), entry)
	tmp := changelogPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(updated), 0o644); err != nil {
		_ = os.Remove(tmp)
		return false, false, fmt.Errorf("changeloggen: write tmp: %w", err)
	}
	if err := os.Rename(tmp, changelogPath); err != nil {
		return false, false, fmt.Errorf("changeloggen: rename: %w", err)
	}
	return true, false, nil
}

// ReadGitLog runs `git log --pretty=format:%H<SEP>%s <from>..<to>` and
// parses output into Commits. Returns ErrNoCommits when the range is
// empty (caller can decide to write a placeholder entry or skip).
var ErrNoCommits = errors.New("changeloggen: no commits in range")

func ReadGitLog(repoRoot, fromRef, toRef string) ([]Commit, error) {
	const sep = "\x1f"
	cmd := exec.Command("git", "log", "--pretty=format:%H"+sep+"%s", fromRef+".."+toRef)
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("changeloggen: git log: %w", err)
	}
	body := strings.TrimSpace(string(out))
	if body == "" {
		return nil, ErrNoCommits
	}
	var commits []Commit
	for _, line := range strings.Split(body, "\n") {
		parts := strings.SplitN(line, sep, 2)
		if len(parts) != 2 {
			continue
		}
		commits = append(commits, Commit{SHA: parts[0], Subject: parts[1]})
	}
	return commits, nil
}

// VerifyRef reports whether the given git ref resolves inside repoRoot.
func VerifyRef(repoRoot, ref string) error {
	cmd := exec.Command("git", "rev-parse", "--verify", ref)
	cmd.Dir = repoRoot
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("changeloggen: ref does not exist: %s", ref)
	}
	return nil
}

// IsSemver reports whether s matches X.Y.Z (no leading "v").
var semverRE = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`)

func IsSemver(s string) bool { return semverRE.MatchString(s) }

// ResolveChangelogPath returns <repoRoot>/CHANGELOG.md.
func ResolveChangelogPath(repoRoot string) string {
	return filepath.Join(repoRoot, "CHANGELOG.md")
}
